### ISSUE TITLE
Unable to Connect GitHub Organization to Jira Site

### ISSUE THREAD

**Issue by SimB4t1qbit** [atlassian/github-for-jira#1012]
Hi there,

I have already installed Jira on the GitHub org highlighted below:
![image](https://user-images.githubusercontent.com/38674018/148135167-11cb3766-3853-4deb-96a9-3c19b567be60.png)

Here is the specific configuration:
![image](https://user-images.githubusercontent.com/38674018/148135351-d88e7f15-711d-4597-8ab0-973c8592566d.png)

But when I attempt to connect the org to our Jira site, I do not see the specific org that I configured above:
![image](https://user-images.githubusercontent.com/38674018/148135295-1cf3fff8-8d18-4ab6-8e9d-591ab44c0556.png)

When I click on "Install GitHub for Jira on a new organization" I am brought back to the first screenshot.

**Comment by thombergs** [comment]
Hey @SimB4t1qbit,

the workflow is not really user-friendly here, sorry about that. 

Have you tried clicking the button "Connect GitHub organization" on the main configuration screen again? The new org (`synthesishealth` in your case) *should* show up in the list then, and then you should be able to connect by clicking the "Connect" button next to it.
 
![image](https://user-images.githubusercontent.com/1363578/148331135-af209ea7-c21f-4ec4-9298-4b5384009666.png)

If that's not the case, please try uninstalling the app from your GitHub org again and then click the button "Install GitHub for Jira on a new organization" again and go from there. 

Let me know if this issue persists.

**Comment by SimB4t1qbit** [comment]
@thombergs clicking on the "Connect GitHub organization" within Jira displays the same result as before (i.e. the new GitHub org is not shown, despite already being configured for Jira):

![image](https://user-images.githubusercontent.com/38674018/148418740-10b0e8a3-eb23-4d3c-ae1b-52b20e8329c2.png)

I have since reinstalled the application on both Jira and GitHub but the issue persists.

**Comment by eran-medan** [comment]
I have the same issue. Note that we moved a repo to a new organization, maybe something is permanently cached on your end?

**Comment by bgvozdev** [comment]
Hi @SimB4t1qbit @eran-medan could you please confirm that you are the Admins of the orgs you are trying to connect?

**Comment by eran-medan** [comment]
@bgvozdev admin both on github and Jira side. The app is installed on the github side but Jira doesn’t seem to identify it. It worked in the past but we had to change to another github org and then it stopped working.

**Comment by SimB4t1qbit** [comment]
@bgvozdev Yup admin on all.

**Comment by bgvozdev** [comment]
@eran-medan @SimB4t1qbit thanks for the reply. I'm currently adding some verbose logging for you folks to see if they could help figuring out what's going on. Will keep you posted!

**Comment by bgvozdev** [comment]
Hey @SimB4t1qbit @eran-medan thanks for your patience. I've added and enabled debug logging for your Jiras, could you please refresh the page with the missing org?

**Comment by SimB4t1qbit** [comment]
@bgvozdev done

**Comment by bgvozdev** [comment]
Thanks @SimB4t1qbit for doing this . So, from what I can see, the org you want to connect is not returned by GitHub API for some reason during this rest call (done with you as the authenticated user):

https://octokit.github.io/rest.js/v18#apps-list-installations-for-authenticated-user

```
Lists installations of your GitHub App that the authenticated user has explicit permission (:read, :write, or :admin) to access.
.....
The authenticated user has explicit permission to access repositories they own, repositories where they are a collaborator, and repositories that they can access through an organization membership.
You can find the permissions for the installation under the permissions key
```

I'm looking further, but sharing this early with you just in case it rings any bells.

**Comment by eran-medan** [comment]
@bgvozdev uninstalled and reinstalled

**Comment by bgvozdev** [comment]
Hey @eran-medan , thanks for doing this. Just double-checking, you have also tried clicking on 
![image](https://user-images.githubusercontent.com/20631664/148701585-702bec81-9401-44b4-99c3-fd8991d955f8.png)
button, haven't you?

**Comment by eran-medan** [comment]
Yep

**Comment by bgvozdev** [comment]
Hey @SimB4t1qbit @eran-medan  After talking to @thombergs , I think it is best to engage with GitHub support for future investigation. We can do it ourselves, however the experience shows it takes quite some time for us to get their reply, therefore maybe you could initiate that talk yourself?

I've added some more logging: if you could please navigate once again to https://github.atlassian.com/session/github/configuration then I could send you the request ID that you could pass along to the support.

The template of the support request might be as following:

> Dear GitHub Support,
> 
> Could you please help me to understand why`/user/installations` API call doesn't return %INSERT_YOUR_DESIRED_ORG_NAME% organisation, despite the fact that I have installed "GitHub for Jira app" in it?  The request ID is `%INSERT_REQUEST_ID_HERE%`.
>
> (For reference: this request is a spin-off from https://github.com/atlassian/github-for-jira/issues/1012)
>
> Thank you.

Sorry that it takes too long to resolve the issue. :(

**Comment by eran-medan** [comment]
Hi @bgvozdev, all is good :) thanks for the support! since this is public, is there any issue sharing a request ID or it's completely opaque with no value whatsoever? Or you can email me directly (I assume if you have the request ID you probably have my email...). Thanks!

**Comment by SimB4t1qbit** [comment]
Not sure what happened, but it seems to be working now!

![image](https://user-images.githubusercontent.com/38674018/148810881-82652d2d-a980-4455-b4b3-f935ec402dd2.png)

![image](https://user-images.githubusercontent.com/38674018/148810915-e678c7d3-5784-4f89-83ef-0db90556592a.png)

**Comment by bgvozdev** [comment]
Hey @eran-medan , request ID is just a random UUID, I doubt there's any risk of sharing it publicly, however if you are concerned you could send me a message to 
![image](https://user-images.githubusercontent.com/20631664/148844218-da41aff1-2f0c-41a5-bdfd-b8036feeb762.png)
and I'll reply with the requestId to you. Whatever works best for you.

@SimB4t1qbit 🤷  glad it works for you now, although we haven't changed anything on our end. As I mentioned earlier, that's GitHub API and I have no idea why it didn't return your org. Unfortunately, we don't have control over this.

**Comment by joasve** [comment]
@bgvozdev I am also having the exact same issue as you when trying to set up the app for our org. Have you had any luck so far?

**Comment by joasve** [comment]
@eran-medan I am also having the exact same issue as you when trying to set up the app for our org. Have you had any luck so far? Our Jira instance doesn't seem to save the configuration.

**Comment by rachellerathbone** [comment]
Hey @SimB4t1qbit @eran-medan. Apologies that this has gone quiet. @bgvozdev has been out on leave but will be back tomorrow 🎉 Please let us know if you're still having issues and he can help follow it up.

**Comment by jatorna** [comment]
Hi, I have the same issue. I can't see my organization when I try to connect with Jira. Do we know how @SimB4t1qbit solved the issue?

**Comment by jatorna** [comment]
@rachellerathbone @eran-medan @bgvozdev, are there any news about this topic?
Thanks!

**Comment by RaphaelDegrave** [comment]
same issue. My account is having admin right in my organisation but JIRA do not recognise my organisation as one of the connected organisation. Does anyone have any hint how to fix it?

**Comment by DerekMart** [comment]
Same issue: console shows "jquery.min.js:2 POST https://github.atlassian.com/github/configuration 500" after clicking on the Connect button.

**Comment by RaphaelDegrave** [comment]
This is a major issue… I wrote to GITHUB support but their reply was to contact JIRA support for which they will certainly ask
To contact the plugin provider which will then bring us here…

**Comment by RaphaelDegrave** [comment]
For everyone's sake, the problem is how JIRA resolves the path to GITHUB. It goes to the easier path, which is to reach your personal account first (also admin account of your organisation)... Below is what you need to do :

1. Go to https://github.com/settings/apps/authorizations and revoke all authorisation (PERSONAL ACCOUNT)
2. Go to https://github.com/settings/developers and revoke all authorisation (PERSONAL ACCOUNT)
3. Go to https://github.com/organizations/{YOUR-ORG}/settings/applications and revoke all authorisation (ORG ACCOUNT)
4. Go to https://github.com/organizations/{YOUR-ORG}/settings/installations and revoke all authorisation (ORG ACCOUNT)
5. Open incognito browser and go to https://{YOUR-ORG}.atlassian.net/plugins to install GITHUB PLUGIN
6. Click on Configure integration and click on Connect an organisation  
7. When prompt to login GITHUB, use you corporate login (Single-sign-on)
8. Authorise the implicit OAuth for your ORGANISATION account through your PERSONAL account (this step is key and is not the same as the JIRA PLUGIN)
9. Install JIRA PLUGIN to the ORGANISATION

**Comment by rachellerathbone** [comment]
Hey @DerekMart @jatorna @joasve. As we haven't heard from you in almost 2 months, I'm going to go ahead and close this issue. If you still need assistance, please feel free to reopen and we can look into this problem for you.
