### ISSUE TITLE
Support For Datacenter

### ISSUE THREAD

**Issue by YashJaitawat** [atlassian/github-for-jira#1017]
Hi,
We have used this plugin for a long time on JIRA server v7.12.1
Now we are planning for upgrading it to Data Center v8.20
This plugin is incompatible with JIRA Data Center. Please help us with the below questions w.r.t compatibility with JIRA Data Center:
 
Questions:
 
Que #1: Are you planning to make the plugin compatible with JIRA Data Center v8.20 in upcoming releases?

Que #2: If yes for Que #1 then when you will be releasing the compatible version?

Que #3: If no for Que #1 then could you please suggest any alternate plugin which will be available for JIRA Data Center v8.20?

**Comment by ccrolf** [comment]
Hi @YashJaitawat , this integration is for Jira Cloud only. The preferred integration mechanism for Jira DC is to use the [DVCS connector](https://confluence.atlassian.com/adminjiraserver/integrating-with-development-tools-using-dvcs-1047552689.html). 

If your run into issues with DVCS, Atlassian support are happy to help you to get it working well for your setup :)
