### ISSUE TITLE
Clone atlassian account - How should the GitHub for Jira application and its data be migrated?

### ISSUE THREAD

**Issue by vcavaco** [atlassian/github-for-jira#1039]
Hello,
I'm going to create a new atlassian account and import my old account into this new one. I understand that plugins are not migrated, so I will install the plugin again in the new atlassian account.

My question is do I just have to install the plugin or do I have to retrieve some information from the plugin about the migrated projects that use it before the migration. Or Have I configure again the account manually?

Version:1.1.8-AC

Regards.

**Comment by mboudreau** [comment]
Configure it in the new account once migration is done. It'll backfill all historical data and you can continue your work from there :)
