### ISSUE TITLE
Only last task is updated as released

### ISSUE THREAD

**Issue by rachellerathbone** [atlassian/github-for-jira#1041]
Opened from https://github.com/atlassian/github-for-jira/issues/855#issuecomment-1017503556

**Comment by palexcast** [comment]
@rachellerathbone I was going to try to provide more details and tried to replicate the issue, but it seems I can't replicate it.

Everything seems to be working as expected now. 
Thank you anyways :)!

**Comment by ccrolf** [comment]
Thanks for your update @palexcast ! :)
