### ISSUE TITLE
Some branches are not reflected on Jira Tickets if they were synched during the backfill 

### ISSUE THREAD

**Issue by KAbakumovAtl** [atlassian/github-for-jira#1045]
We have some customers reporting the problem of not seeing branches on Jira tickets after the migration from Jira Server to Jira Cloud and switching from DVCS Connector to "GitHub  for Jira App" for GitHub Integration

We are currently working on investigating this problem and we'll keep you updated about the progress.

**Comment by nvigo** [comment]
Hi @KAbakumovAtl any progress on the fix for this issue, please?
Any ETA to get the fix deployed?
Thanks!

**Comment by mattborja** [comment]
I also raised an issue with support that might be related (JSF-4519).

Reinstalled the app on both sides (Jira and GitHub) and attempted backfill, but have been unsuccessful getting anything to link up. I'm also told that my PRs and branches followed the naming convention for linking, but was then advised to go chase down communities, etc. that I just haven't had time to do.

I expressed that I'm going to need to find another plugin soon if I can't get this to work. Would love to know whether this is in fact related and under investigation.

Thanks.

**Comment by ccrolf** [comment]
Hi @mattborja , nothing showing up after backfilling is likely a very different problem. A few missing data points is expected for large backfills, as some REST API calls to GitHub fail regardless of which retry strategy we use.

We released a fix for the install flow last week, can you try uninstalling and reinstalling again? The repo you shared seems to have multiple commits and PRs that should be linked. Note that deleted branches will not be linked to Jira issues.

**Comment by nvigo** [comment]
Hi @ccrolf , Has the fix that you mention solved the issue regarding some Branches not shown? From where I can download that new version for this Plugin with the fix you mention pls?
Thanks in advance!

**Comment by rachellerathbone** [comment]
Hey @nvigo. Apologies for the slow response. Is this something you still need help with?

**Comment by rachellerathbone** [comment]
Hey @nvigo. As we haven't heard from you in almost 2 months, I'm going to go ahead and close this issue. Please feel free to reopen if you still need assistance.
