### ISSUE TITLE
There is not "Get Started" button

### ISSUE THREAD

**Issue by pangtongs** [atlassian/github-for-jira#1058]
Hi. I am new to this system and when trying to install the app, I cannot find any "Get Started" button on this page. 
What did I do wrongly?

![image](https://user-images.githubusercontent.com/6629520/151772883-02d2e2bb-bf70-4092-9a2e-427eed634b8d.png)

**Comment by mboudreau** [comment]
When you installed it, there would have been a modal that would have popped up with a 'Get started' button.  If no, you can also get there by going to `https://<your jira subdomain>.atlassian.net/plugins/servlet/upm` and clicking the "configure integration" under the Github header in the sidebar.  Then just add your Github organization and you're ready to roll.
