### ISSUE TITLE
Excessive time to perform backfill on few repositories

### ISSUE THREAD

**Issue by joshes** [atlassian/github-for-jira#1071]
We are trying to backfill 13 repos (we're using selected repos, not "All Repos") and the backfill process has been running for just under 24h so far which seems excessive. 

- Is it hung? 
- Why is it so slow? 
- Is there anything we can do to get it to complete?
- How to debug?

According to the count in the UI, we're on 13/234 repos & we have 20 projects in Jira.

<img width="646" alt="Screen Shot 2022-02-04 at 7 45 00 AM" src="https://user-images.githubusercontent.com/626427/152558635-cd4d8d08-62a9-49c8-9fc2-543692aaf958.png">

I did restart the backfill process twice yesterday if that plays into the issue at all.

Anything we can do to help get this to finish?

**Comment by atrigueiro** [comment]
Hi @joshes, unfortunately, the sync process is currently really slow, so it can take days or even weeks for a sync to complete, depending on the number of commits in the repos. We're working on making it faster, but that will take some time.

There's nothing you can do on your end to help to get it to complete, however, restarting won't help either - will actually just start the process all over again.

I can have a look in our logs to make sure there's no errors happening though, what's your Jira instance?

Meanwhile, I can only recommend that you wait until the process finishes.

Thanks.

**Comment by joshes** [comment]
If it's a known issue, I guess that's it, but ours has been running for a few weeks now and has only gotten through 13 repos out of many. I just checked and it was still running and still on 13. I restarted it. 

What are the factors in making it take so long? _WEEKS_ feels a bit excessive in any scenario.

**Comment by rachellerathbone** [comment]
Hey @joshes. Something is certainly amiss here. We've known the sync to be slow on repos with large amounts of historical data but weeks is definitely excessive. As your last message is several weeks old, please let me know if you are still facing this issue and I can look into it for you.

**Comment by rachellerathbone** [comment]
Hey @joshes. As we haven’t heard from you in a while, I’m going to go ahead and close this issue. Please feel free to reopen if you still require assistance.
