### ISSUE TITLE
only the first PR is linked to the JIRA issue

### ISSUE THREAD

**Issue by Angel-O** [atlassian/github-for-jira#1072]
Hi, I was wondering the following:

is there a 1-to-1 relationship between Github pull requests and jira issues?

It looks like the JIRA ticket will only list a single PR.

if more than one PR are linked (by prefixing the branch name with the ticket ID) to the JIRA ticket they won't be listed under the `Details` panel (`Development` section )

Is there a way to change this behaviour so that every PR gets linked to the ticket? 

Thank you

**Comment by atrigueiro** [comment]
Hi @Angel-O, 

I've just tested this scenario and it is working as expected here - multiple PRs are associated with the Jira issue when the key is added to the branch name or PR title - see screenshot below.

<img width="326" alt="Screen Shot 2022-02-11 at 2 41 01 pm" src="https://user-images.githubusercontent.com/58801956/153534229-0a0e7ef3-f935-4674-9516-10a943450a04.png">

Are you sure you've added the Jira issue key correctly, maybe it had a typo?
If it's still happening on your end, please inform your Jira instance and the Jira issue key in question and I'm happy to have a look at our logs.

Thanks,
Amanda.

**Comment by Angel-O** [comment]
Hi Amanda, 

Thank you for your reply. I've realized that the issue wasn't there. I should've updated the ticket, apologies.

What I've noticed though is that multiple branches don't seem to be supported. I had  instance where I was expecting to see at least 2 branches, one per PR, but I could only see one.

I will double check next week and confirm.

Thank you

**Comment by atrigueiro** [comment]
All good @Angel-O, thanks for the heads up. I'll close this issue now. Cheers.
