### ISSUE TITLE
JIRA projects with a total number of tickets greater than 1000 will not be linked

### ISSUE THREAD

**Issue by wores** [atlassian/github-for-jira#1073]
When commenting xxx-123 on a GitHub Issue, only projects with more than 1000 tickets are not linked.
Is there something wrong with my settings? 
Synchronization between GitHub and JIRA has been completed successfully.

I don't know the exact threshold of the total number of tickets that will not be linked.
Projects with total number of tickets around 800 will be linked.

**Comment by rachellerathbone** [comment]
Hey @wores. Apologies for the incredibly slow response to this.

Is this still an issue for you? This is not something we have observed. Our team uses Jira for project management and are nearing the 2000 ticket mark. All issues are connected so long as the team includes the issue key in their commits, branches, PRs etc

**Comment by rachellerathbone** [comment]
Hey @wores. As we haven’t heard from you in almost 2 months, I’m going to go ahead and close this issue. Please feel free to reopen if you still need assistance.
