### ISSUE TITLE
GitHub organization not persisting in the Jira configuration

### ISSUE THREAD

**Issue by joasve** [atlassian/github-for-jira#1074]
When attempting to configure the app, we are having issues with Jira not “remembering” or persisting the settings. I have been successful in installing the app for both endpoints (Github, Jira), however in Jira, it seems like it keeps looping back to the page titled “Connect a GitHub organisation to your Jira site” - and below it gives me the message that “No Github organisations with Jira installed”, although I have set this up multiple times already. I have been in contact with Github Support who referred me to reach out to Atlassian Support for help with this. Github Support also confirms that they are able to see successful API requests on their end. Could you please help me look into this?

**Comment by joasve** [comment]
Update: got it working now. It appears there's some kind of bug in the deployment phase on the Jira side. Unless all steps are performed in a certain order, the setup will fail, and the user does not get any type of error or status message at all. This should really be brought up internally as an RFE.

**Comment by joasve** [comment]
Feel free to close out this ticket.

**Comment by atrigueiro** [comment]
Hi @mattlavinder, I'm one of the developers from Atlassian working on this integration and can confirm that we do monitor the issues here on a weekly basis. We'll be more than happy to help you if provide some screenshots or steps to reproduce the issue you're having. Cheers.

**Comment by joasve** [comment]
@mattlavinder I had to uninstall/re-install the app on both ends at least a dozen times before getting it to work, but was finally successful. Try following the official documentation (https://github.com/atlassian/github-for-jira/blob/old-master/README.md) exactly to a tee, because it seems that the slightest wrongful click will cause the integration to fail.

**Comment by rachellerathbone** [comment]
Hey @mattlavinder sorry to hear you had so many issues try to get the integration up and running. Do you have any specific examples of issues you ran into so we can potentially look into areas to improve?

**Comment by rachellerathbone** [comment]
Hey @joasve. As we haven't heard from you in a while, I'm going to go ahead and close this issue. Please feel free to reopen if you still require assistance.
