### ISSUE TITLE
How to disable - Create a Branch - feature

### ISSUE THREAD

**Issue by vinyldeveloper** [atlassian/github-for-jira#1124]
We use "Github for Jira" to link our Jira tickets to our Github tickets, but we have our own process for creating branches, creating pull requests, merging, and deleting branches. 

We would like to disable the "Create a Branch" link and confirm that Jira isn't performing any other modifications to our repository. 

![image](https://user-images.githubusercontent.com/35709769/158187518-8222866e-2624-486d-b10f-e97b9d6ccd93.png)

The documentation for this plugin says it requires read/write access in order to set up webhooks:

![image](https://user-images.githubusercontent.com/35709769/158186956-979ba31d-ba6e-4e32-9f5e-c3bebf5d49ce.png)

The documentation doesn't mention modifying the repository, which can be very disruptive to the development process. It also doesn't mention the "Create a Branch". Is there a way to disable this?

Thank you for any information you can provide.

**Comment by mboudreau** [comment]
This is not a Github for Jira specific issue, but one within Jira itself.  This problem would arise using any other source code integration.  [Sadly, it seems like this is not supported yet, but I would recommend you vote for the issue to be resolved by an Atlassian Jira team member](https://jira.atlassian.com/browse/JSWSERVER-14931).  A "workaround" is to disable the Development View altogether, which is sub-optimal.

Sorry I can't give you better news. I'll be closing this ticket as it's not related with the integration.
