### ISSUE TITLE
Development data not consistent with previous DVCS integration

### ISSUE THREAD

**Issue by msmithmio** [atlassian/github-for-jira#1135]
Hello,

Migrating from Server to Cloud. Server leverages DVCS, Cloud using this add-on. 

**Server project showing:**
1 branch
4 commits
1 pull request

**Cloud project showing:**
0 branches
1 commit 
1 pull request

Please advise

**Comment by mboudreau** [comment]
Did the app finished syncing before you looked?  We need more information before we can investigate.  Can you show us screenshots of the repo in question (of the information you want to see), the name of the repo, the name of the github org, the jira instance url, etc.

Thanks.

**Comment by mboudreau** [comment]
@msmithmio Actually, we discovered that the Github API had some issues recently.  Could you try restarting the backfill of your organization to see if it fixes the issue?  Thanks.

**Comment by mboudreau** [comment]
I will assume that the issue was resolve and close this.  Feel free to open it if you're having any more issues.  Cheers.
