### ISSUE TITLE
Permissions: Read access to actions?

### ISSUE THREAD

**Issue by C0x41lch0x41** [atlassian/github-for-jira#1138]
The doc mentions that the app needs [read access to GitHub Actions](https://github.com/atlassian/github-for-jira/blob/main/README.md#jira-permission-scopes). However during the installation flow, access to github actions is not mentioned:
<img width="382" alt="Screen Shot 2022-03-22 at 8 10 44 PM" src="https://user-images.githubusercontent.com/13424297/159616419-40cbe58f-3ece-465f-b4bb-f4652b1d3551.png">

Which one is true?

Thanks.

**Comment by mboudreau** [comment]
Both.  The documentation (3rd row of the table) says that we need read and write access for issues and PRs.  This is to update your issue/PRs with a link to a ticket id when added to a comment or description.  There is no way of doing a 'read only' version easily with Github without creating a separate app and infrastructure.

**Comment by mboudreau** [comment]
Sorry, I misread.  I think someone pre-emptively added github actions in there to read from when we get a webhook trigger for `workflow_run`.  It's currently not being used and docs should be updated.

**Comment by C0x41lch0x41** [comment]
Thanks for the answer.
Best
