### ISSUE TITLE
"This organization's IP address is blocked" error after confirming all IP's are allowed

### ISSUE THREAD

**Issue by alexishuefner-taulia** [atlassian/github-for-jira#1152]
I have confirmed all IP ranges (including the individual ones list in the Issues with API allowlist box here: https://github.com/atlassian/github-for-jira/blob/main/docs/ip-allowlist.md) and I am still getting the error in the attached screenshot. Any suggestions on what I can try next? Thanks!
<img width="778" alt="Screen Shot 2022-04-05 at 3 14 46 PM" src="https://user-images.githubusercontent.com/45047585/161851020-f1b0bc1b-5fe8-46f3-8205-c336fd474945.png">

**Comment by mboudreau** [comment]
@alexishuefner-taulia Looking at the logs, Github is clearly saying that it's blocked from the `taulia-trade-tech` org.  Do you have both IP Allowlisting checkboxes checked for your org as per the documentation?

**Comment by bgvozdev** [comment]
Hey @alexishuefner-taulia , we've just merged some more debug logging around this. If you can refresh the page, we could check what exactly IP GitHub was blocking so you could double-check the config on your end.

**Comment by alexishuefner-taulia** [comment]
Hi @bgvozdev - Sorry for the delay. What page did you need me to refresh? Thanks for the help!

**Comment by bgvozdev** [comment]
hey @alexishuefner-taulia , no worries, I see you have already refreshed the page (I meant the config page where you see the error :) )

Here's the error message that GitHub returns:

> Although you appear to have the correct authorization credentials, the `taulia-trade-tech` organization has an IP allow list enabled, and 13.52.5.105 is not permitted to access this resource.

Could you please double-check that you have this IP in your allowlist? Thanks!

**Comment by alexishuefner-taulia** [comment]
@bgvozdev I checked in github and the IP you provided is on the allowlist. Do I need to also add it manually? 
I also checked our Atlassian environment and we don't have allowlisting enabled there. 
I've attached screenshots for reference. Thanks for your help!
<img width="932" alt="Screen Shot 2022-04-07 at 7 56 38 AM" src="https://user-images.githubusercontent.com/45047585/162216905-8afc1baa-d6b8-41ec-b70c-dd42de1ad2bf.png">
<img width="1341" alt="Screen Shot 2022-04-07 at 7 57 05 AM" src="https://user-images.githubusercontent.com/45047585/162216911-5dab095f-437b-49e3-b74d-a3e378cba64a.png">

**Comment by bgvozdev** [comment]
Hey @alexishuefner-taulia , did you add it to GitHub org as an individual IP or as a part of the CIDR range?

> ⚠️ Issue with IP allowlists! Currently, there is an issue with IP allowlists. GitHub blocks some requests to the API even if the correct IP addresses are listed in the IP allowlist. To work around this problem, you have to add the IP addresses 13.52.5.96 through 13.52.5.111 to your IP allowlist (each IP address individually, not as a CIDR range).

**Comment by mboudreau** [comment]
@alexishuefner-taulia Any updates on this?  I'll close it if it's been fixed or we don't hear back from you.  Cheers.

**Comment by alexishuefner-taulia** [comment]
I was able to get it fixed. I did not realize that I had to add the IP's manually even if they already existed on the allow list. Once I added them again then it worked. 
Thanks for the help!

**Comment by mboudreau** [comment]
@alexishuefner-taulia you don't need to add them manually, if they're in the list.  You just need to enabled then by clicking the `Enable IP allow list configuration for installed GitHub Apps` checkbox above it as [mentioned in the docs](https://github.com/atlassian/github-for-jira/blob/main/docs/ip-allowlist.md) :)

**Comment by alexishuefner-taulia** [comment]
Yeah, I did all of that and it didn't work until I added them manually. It's all good though, it's working now. Thanks!

**Comment by mboudreau** [comment]
@alexishuefner-taulia That's annoying.  I think Github's been having some issues with their IP allowlisting feature for a few months now.  They broke CIDR ranges on it a while back and we had to input each IP manually :|
