### ISSUE TITLE
Development tab will sometimes not sync.

### ISSUE THREAD

**Issue by JOcampoCR** [atlassian/github-for-jira#1166]
Specifically in jira under development tab pr will show open but in git it is merged. Is there a work around for this?

**Comment by mboudreau** [comment]
Can you try restarting the sync in the Github app configuration?  We believe we've fixed and issue and resyncing it should show the correct data again.  Thanks!

**Comment by JOcampoCR** [comment]
I will give this a try may take a bit since i dont have permissions. Do i need to do this to resolve future issues or is just for the issues that are already not synced?

**Comment by mboudreau** [comment]
@JOcampoCR This is just a one time fix as we've identified something that didn't sync in the past.  From now on, everything should work as intended.

**Comment by rachellerathbone** [comment]
Hey @JOcampoCR. Do you need any further assistance on this one?

**Comment by rachellerathbone** [comment]
Hey @JOcampoCR. As we haven’t heard from you in almost 2 months, I’m going to go ahead and close this issue. Please feel free to reopen if you still need assistance.
