### ISSUE TITLE
Feature request: Add preview to development environment mapping

### ISSUE THREAD

**Issue by mwisner** [atlassian/github-for-jira#1190]
Hi,

At companies I've worked at recently, the word 'preview' is used regularly to describe environments where we deploy code before being accepted into the codebase. (preview deployments)

I was wondering if it might be possible to add `preview` or `review` to the array of development env mapping: https://github.com/atlassian/github-for-jira/blob/main/src/transforms/transform-deployment.ts#L141-L146

It looks like they are reworking the gitlab integration, but https://gitlab.com/gitlab-org/gitlab/-/merge_requests/80539/diffs#4868aa0ea6e830fd12667a79037bb1969b769a59_30_23 gitlab jira has `review` under development as well.

**Comment by rachellerathbone** [comment]
Hey @mwisner. Please see this comment on one of our other issues for an update on deployment mappings. https://github.com/atlassian/github-for-jira/issues/1303#issuecomment-1226715001

**Comment by rachellerathbone** [comment]
Hey @mwisner. I hope that our deployment mappings were able to help address your needs. I'm going to go ahead and close this issue. If you still need further assistance, and the deployment mappings don't quite address what you are after, please feel free to reopen this issue.
