### ISSUE TITLE
Cannot connect Github to Jira plugin

### ISSUE THREAD

**Issue by Pumeo1010** [atlassian/github-for-jira#1192]
Hi,
My team has a problem when trying to connect Github repo to Jira plugin. After adding desired repos and submitting them, this error kept showing:
![image](https://user-images.githubusercontent.com/38429998/168542114-7ea8de8d-b30e-4f3a-9431-fc9241850ba9.png)

We have tried with both private and public repos but nothing worked.

Please help us.

**Comment by mboudreau** [comment]
Could you please try to record your screen of going through the process of connecting and organization please?  It's kinda hard to tell what's going on from this image alone.  Thanks :)

Also, what's your jira domain so we can look through the logs?

**Comment by rachellerathbone** [comment]
Hey @Pumeo1010. As we haven’t heard from you in a while, I’m going to go ahead and close this issue. Please feel free to reopen if you still require assistance.
