### ISSUE TITLE
Can't install Github for Jira App

### ISSUE THREAD

**Issue by miwhitle** [atlassian/github-for-jira#1195]
I installed the "Jira Software + Github" app in our Github account, but when redirected to our Jira account as part of the install, I see the following message:

![Screen Shot 2022-05-18 at 1 56 37 PM](https://user-images.githubusercontent.com/40034966/169140259-f6fecec2-d626-45fc-bd31-c861fd5df610.png)

Next, I tried searching in the Marketplace for the "GitHub for Jira" app which yields zero "Atlassian Developed" results. 

I then browsed to the public page for the app here: https://marketplace.atlassian.com/apps/1219592/github-for-jira?tab=overview&hosting=cloud and clicked the "Get it now" button. This gave me the following message that the app was "Added".

![Screen Shot 2022-05-18 at 2 28 07 PM](https://user-images.githubusercontent.com/40034966/169140740-5dd67d53-143a-4ae5-b37e-27617a783d35.png)

But the app is not actually installed and can not be found anywhere in the "App" menus of our Jira account.

**Comment by mboudreau** [comment]
@miwhitle I'll look into that error when installing from github - do you have admin permissions on the jira instance?  The github configuration is under the `manage apps` section under the `apps` menu - this is outside of our control as it's how connect apps work in jira (sadly). Or you can try this URL to access the app directly: https://<your_instance>.atlassian.net/plugins/servlet/ac/com.github.integration.production/github-post-install-page

**Comment by rachellerathbone** [comment]
Hey @miwhitle. Are you still facing this issue?

**Comment by rachellerathbone** [comment]
Hey @miwhitle. As we haven’t heard from you in almost 2 months, I’m going to go ahead and close this issue. Please feel free to reopen if you still need assistance.

**Comment by xascar** [comment]
@rachellerathbone I'm still facing the same issue as @miwhitle, this is the message when I try to access directly to the link @mboudreau 
https://team-16695154210216.atlassian.net/plugins/servlet/ac/com.github.integration.production/github-post-install-page
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/8994634/210191244-f4fa6bcc-3c69-4815-a1a6-f043d4032288.png">

Also it seems like if it were already there 

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/8994634/210191292-fc114ca1-d267-4bc6-ba98-c713d79fd825.png">

**Comment by idNoRD** [comment]
The solution is to use a different browser. 
I had the "Something's gone wrong" message on Chrome.
When I tried Opera browser the same page had opened successfully.

**Comment by zergeborg** [comment]
@rachellerathbone Could you please re-open this issue?

I face the exact same problem that `xascar` and `miwhitle` was facing. And to top that off I cannot browse repositories in one of the Github organizations that I belong to any more(!!!). Even though browsing repositories worked all right just a month ago.
