### ISSUE TITLE
Detecting commits

### ISSUE THREAD

**Issue by ajtruckle** [atlassian/github-for-jira#1204]
Hi !

I think this app is awesome. :)

When I first installed it it did all the scanning in the background and worked out all the commits and repositories etc. Great.

But, today I added a new repository to GitHub. And then I created a new project in Jira. I started a new ticket and made some changes. I pushed the changes and tagged the commit with the correct tag.

But, for some reason, the Github for Jira is not detecting these commits. What must I do?

Thanks!

**Comment by ajtruckle** [comment]
I went to the Github Configuration and restarted the backfill. That has completed. But my new issue has not detected the commit.

**Comment by mboudreau** [comment]
Did you specify that the app has access to all repositories or only a select few?  I can also check the logs if you can provide us with your atlassian domain, thanks :)

**Comment by ajtruckle** [comment]
Hi @mboudreau 
Yes, it has full access to all 9 repositories. Here is my domain: https://trucklesoft.atlassian.net/

**Comment by mboudreau** [comment]
@ajtruckle I just looked in the database and I don't see your domain in there.  Are you sure you installed our app?  there are a few others with similar names on the marketplace (I know, confusing).  Also, after you install it, you need to configure it to connect it to your Github org from Jira, did you do that step?

**Comment by ajtruckle** [comment]
<img width="1280" alt="Screenshot 2022-06-10 at 08 18 04" src="https://user-images.githubusercontent.com/7985331/173011755-34f4a463-0578-4987-90b4-adfd68ff20d3.png">

I am all set up correctly. Everything works fine. IUt was that single issue tick (which I have since archived on Jira anyway).

**Comment by rachellerathbone** [comment]
Hey @ajtruckle. Apologies that it has been a while since you heard from someone from the team. Can I first confirm if this is still an issue for you?

**Comment by rachellerathbone** [comment]
Hey @ajtruckle. As we haven’t heard from you in almost 2 months, I’m going to go ahead and close this issue. Please feel free to reopen if you still need assistance.
