### ISSUE TITLE
Data Security Evaluation for a client

### ISSUE THREAD

**Issue by phlohauer** [atlassian/github-for-jira#1205]
Dear Madam or Sir,
 
As part of a data protection evaluation of one of our Atlassian clients, it is necessary to provide information on the following aspects and address the following questions referring to your marketplace app "GitHub for Jira":
 
•	Is data stored and protected in accordance with the GDPR and do you have a data security/protection statement to review?
•	Is there a currently valid order processing contract/ agreement of processing in accordance with Article 28 GDPR (German: „Auftragsarbeitungsvertrag“)?
•	Hosting: is the client's data hosted in continental Europe? if so, where are your datacenters located? otherwise, is it possible to host our client's data in the European Union?
 
I would be very pleased to receive an answer to these questions and hope to receive a response soon.
 
Kind regards,
Florian Hauer

**Comment by ccrolf** [comment]
Hi Florian, these questions should all be covered by the official Atlassian documentation on [GDPR](https://www.atlassian.com/trust/privacy/country/europe-and-gdpr) and [data residency](https://support.atlassian.com/security-and-access-policies/docs/understand-data-residency/). 

More context specific for this integration is that Github.com is currently not data resident. A separate, [data resident version of GitHub](https://docs.github.com/en/github-ae@latest/admin/overview/about-data-residency) is currently under development.

**Comment by rachellerathbone** [comment]
Hey @phlohauer. As we haven’t heard from you in a while, I’m going to go ahead and close this issue. Please feel free to reopen if you still require assistance.
