### ISSUE TITLE
Please add the transition command feature for Jira Work Management same as Jira Software

### ISSUE THREAD

**Issue by sushantoghosh** [atlassian/github-for-jira#1208]
Smart Commit commands

There are three commands we can use in your Smart Commit messages:

comment

time

transition

<ignored text> <ISSUE_KEY> <ignored text> #<transition_name> #comment <comment_string>

work with Jira Software but not working with Jira Work management, please fix this.

**Comment by fcce** [comment]
Jira Work Management not working, please fix

**Comment by rachellerathbone** [comment]
Hey @sushantoghosh and @fcce. Unfortunately, the GitHub for Jira app does not control smart commits. Additionally, smart commits are only supported for JSW and not for JWM.
