### ISSUE TITLE
Don't see anything under deployments in my project.

### ISSUE THREAD

**Issue by Sukriti-ss** [atlassian/github-for-jira#1241]
Hi There, 
We have organization set in the global setting for Github for Jira but at project level nothing appears under deployments.

**Comment by mboudreau** [comment]
Have you connected your Github org with Github for Jira?  You need to configure/allow the app first before it can get the data.  The url for the configuration should be something like https://<your-domain>.atlassian.net/plugins/servlet/ac/com.github.integration.production/github-post-install-page

**Comment by Sukriti-ss** [comment]
yes we did and it is working fine for other projects.
Please find attached the error.

![Screenshot 2022-06-08 130337](https://user-images.githubusercontent.com/107077561/172706830-0d09884c-1381-4a3a-84ca-b612dbd29a75.png)

**Comment by mboudreau** [comment]
That's not Github for Jira, this is Cucumber for Jira and has nothing to do with us.

**Comment by VMallineni** [comment]
I followed below steps.
1. Clicked Deployments in left side panel.
2. And then clicked Add another CI/CD tool.
3. Selected Github for Jira.
4. But it shows it's already added.
5. When I go back to the Deployments, It still shows the same.

![image](https://user-images.githubusercontent.com/93206049/172906562-2747dfd5-0dc2-497f-99c1-323d1a272276.png)
![image](https://user-images.githubusercontent.com/93206049/172906789-40b0f9ed-9baa-44b9-b54b-335defc4df85.png)
![image](https://user-images.githubusercontent.com/93206049/172907852-5d8cbbd5-ee87-4337-83be-d638c2236a74.png)
![image](https://user-images.githubusercontent.com/93206049/172908281-e1254139-c024-4f9a-bed5-11b72bae44b4.png)

**Comment by mboudreau** [comment]
Can you please go under `Apps` in the top menu, then click on `Manage Apps`.  Then click on the `Github For Jira` on the side menu and take a screenshot?  Thanks :)

**Comment by VMallineni** [comment]
When I go to more in the top menu and selected Apps. This is what I see.

![image](https://user-images.githubusercontent.com/93206049/173111482-0cd7aa73-221a-4a79-94e9-32032a83c00f.png)


When I searched for Github for Jira, This is what I am getting.

![image](https://user-images.githubusercontent.com/93206049/173111812-ab6ed47c-4b15-4b3c-98d9-3a2e6b4e5727.png)

**Comment by Sukriti-ss** [comment]
Here you go.
![image](https://user-images.githubusercontent.com/107077561/173112993-e16df0eb-b682-4ec8-b0ca-11afac1a63d6.png)

**Comment by beathorst** [comment]
I have the same problem. 
- Installed the App in Jira and Github
- Configure the connection between

But in the Development section I cannot select Github

**Comment by rachellerathbone** [comment]
Hey @Sukriti-ss and @beathorst. To see builds and deployments data in Jira you need to create workflows for them in each repo linked to Jira. You can find examples of these files here: https://github.com/rachellerathbone/sandbox/tree/main/.github/workflows

**Comment by rachellerathbone** [comment]
Hey @Sukriti-ss and @beathorst. As we haven’t heard from you in almost 2 months, I’m going to go ahead and close this issue. Please feel free to reopen if you still need assistance.

**Comment by ahmed-mrbeam** [comment]
@rachellerathbone I'm facing a similar issue, I can only see github pages deployments on Jira but not any other.
I'm using your example workflows.
