### ISSUE TITLE
Jira to Github - Create Branch issue still happening?

### ISSUE THREAD

**Issue by JHelton1** [atlassian/github-for-jira#1287]
I saw that there was an issue reported when linked from Jira to Github and trying the Create Branch button on Jira.

Apparently, my customer is having the same issue now.  When they click the Create Branch button, it does not work, if they create the branch in Github and come back to Jira, things are okay.

**Comment by mboudreau** [comment]
That current functionality isn't available at the moment from the jira end. We actually have this as a priority coming up next quarter :)

**Comment by rachellerathbone** [comment]
We're officially kicking off work for this next week 🎉  Stay tuned!

**Comment by rachellerathbone** [comment]
Just a quick update. The team working on this is very close to wrapping this project up. Will message again when it's live.

**Comment by rachellerathbone** [comment]
This feature is now fully rolled out 🎉 so closing this issue.
