### ISSUE TITLE
Github for Jira don't see all my organization

### ISSUE THREAD

**Issue by Xoib** [atlassian/github-for-jira#1288]
Hello,

Github for Jira only see one of my organizations: 
![brave_xkJYp8dU3K](https://user-images.githubusercontent.com/511705/174835526-b9ce02c7-5728-45b1-be24-ba9a75948f0e.png)

I am trying to link it with one of my other organization.

In my target organization, within github setting page, the Jira app is correctly installed and rights are given : 
![image](https://user-images.githubusercontent.com/511705/174835648-1edd1373-0424-43b7-87bc-29b94b57584a.png)

Please adivse,

**Comment by mboudreau** [comment]
You need to install the app on the other organization and be the admin of that organization to connect to it.  If you don't meet this requirement, you cannot add a new org to jira for security reasons.

**Comment by Xoib** [comment]
> You need to install the app on the other organization and be the admin of that organization to connect to it. If you don't meet this requirement, you cannot add a new org to jira for security reasons.

Admin on both side, jira atlassian and the targeted github organization.
Still I have this specific problem.

**Comment by mboudreau** [comment]
What's the message that shows when you hover over the 'connect' button?

**Comment by Xoib** [comment]
> What's the message that shows when you hover over the 'connect' button?

The organization seen in my first screenshot is not the one I want to connect to!
The one I want to connect to isn't showing up.
Thus the message when I over on the connect button for the organization already connected doesn't matter, the message is about the fact that for this specific organization I am not admin, which is correct but we don't care, because that's not the organization I want to connect.

The organization I want to connect isn't listed, I am owner of this organization.

**Comment by mboudreau** [comment]
So, you've installed the app on the second organization but it's not
showing up in the list? Do you have IP allowlist enabled on your GitHub org?

**Comment by Xoib** [comment]
Exactly. The app is correctly installed on the targeted organization, and configured like you see on my second screenshot. And this org doesn't show up in the list.

I don't have IP allowlist enabled.

**Comment by mboudreau** [comment]
Okay, I'm going to need to know the GitHub org name and your jira domain to
look at the logs to see what's going on.

**Comment by Xoib** [comment]
Sure, can we communicate those information privately? If yes tell me how.

**Comment by mboudreau** [comment]
Email it to me at mboudreau@atlassian.com
Cheers.

**Comment by Xoib** [comment]
> Email it to me at [mboudreau@atlassian.com](mailto:mboudreau@atlassian.com) Cheers.

Thank you! I sent you the requested information by e-mail. Let me know if you want to do a quick sharing screen call.

**Comment by mboudreau** [comment]
@Xoib Looked at the logs and saw `could not determine admin status of user Xoib in org <YOUR ORG>`.  The github API is returning a 403 status which can happen for a few different reasons, but more often than not it's because IP Allowlisting has been enabled on that specific org or there's simply a problem with the API (unlikely).

If you were to look at this URL to check the IP Allowlisting status: https://github.com/organizations/<YOUR ORG>/settings/security
If IP Allowlisting is enabled, you need to tick the `Enable IP allow list configuration for installed GitHub Apps` checkbox.

If that is not the issue, then we could always get on a call together to figure out the issue.

Cheers.

**Comment by Xoib** [comment]
@mboudreau here a screenshot of how it is (I didn't touch anything) : 
![image](https://user-images.githubusercontent.com/511705/175265210-f742a286-8174-4db3-ab2b-1b5b00b28f63.png)

**Comment by mboudreau** [comment]
Hm, weird.

Do me a favor, go to this url and login/authorize the explorer: https://docs.github.com/en/graphql/overview/explorer

And in the query textfield, copy paste this (replacing the org) and click the play button then show me the result:

```
query { 
  viewer { 
    organization(login: "YOUR-ORG") {
      viewerCanAdminister
    }
  }
}
```

Thanks

**Comment by Xoib** [comment]
Result bellow: 

`{
  "data": {
    "viewer": {
      "organization": {
        "viewerCanAdminister": true
      }
    }
  }
}`

**Comment by Xoib** [comment]
@mboudreau, with a renewed auth after clearing cookies of `github.atlassian.com` domain, it worked, the org I wanted appeared in the list and I was able to click on the connect button. Thank you!
