### ISSUE TITLE
Error reported when clicking Update

### ISSUE THREAD

**Issue by Kristianwhittick** [atlassian/github-for-jira#1339]
When I click the Update button, I get the below error.

![image](https://user-images.githubusercontent.com/6951156/177291849-a1c96314-b867-44d5-98fc-3507ce868d81.png)

**Comment by rachellerathbone** [comment]
Hey @Kristianwhittick. This would be an issue that happens outside of our app. I've reached out to the team who owns installing/updating apps in Jira. Will reach out again when I know more.

**Comment by rachellerathbone** [comment]
Hey again @Kristianwhittick. Can I get the domain for the affected Jira site and the approximate timestamp when you ran into this issue (rough date and time)?

**Comment by Kristianwhittick** [comment]
@rachellerathbone - Thank you for your reply and for looking at the issue.

The domain = https://odx.atlassian.net/jira

It was yesterday - 5 Jul 2022 10:00 BST

**Comment by rachellerathbone** [comment]
Hey @Kristianwhittick. Apologies for the slow response. Are you still facing this issue?

**Comment by rachellerathbone** [comment]
Hey @Kristianwhittick. As we haven’t heard from you in almost 2 months, I’m going to go ahead and close this issue. Please feel free to reopen if you still need assistance.
