### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by PuneetKohli** [atlassian/github-for-jira#135]
Hi,

We're using this plugin at our workplace as a replacement for the previous Jira DVCS connector. Got in touch with @andymckay for how to automatically trigger workflows from Github other than using 'smart commits'.  

Primarily we are looking for deeper integration between Jira Workflows and Github actions.

More specifically, It'd be interesting if we could see some of the below features:-
1. Closing a Jira Issue by closing a PR on Github which has that Issue# (can be a setting) 
2. Moving a Jira issue to "in progress" if a branch or commit has an issue# (and it was previously in todo)
3. Moving a Jira issue to "testing"/"in review" if a PR is opened for that issue# (and it was previously todo/in progress)
4. Automatically highlight Jira Issue IDs in Github and make them clickable links. If it's not possible (for example in a PR title), it could even just be an additional field/button somewhere that says "open in Jira"
5. Create/Delete branch from JIRA

**Comment by PuneetKohli** [comment]
Wondering if someone from the team could let me know if any of these are currently being looked into? Or are on the roadmap.

**Comment by tcbyrd** [comment]
Hey @PuneetKohli! We do not have anything formal to share currently, but there are some new features on the roadmap for both Jira and GitHub that should enable some of these. I like the idea of making some of these configurable options. One idea I had around this is using [probot-config](https://github.com/probot/probot-config), so a repository owner could opt in to certain features. The initial release was aimed primarily at getting feature parity with the DVCS connector, so I'm thinking that anything we add beyond that like other ways to trigger transitions should be something a user can opt in to.

Also we welcome any PRs from users of the integration. I'm definitely willing to offer any review and get things deployed if users are interested in adding the features. Check out the [contributing guideliens](https://github.com/integrations/jira/blob/master/CONTRIBUTING.md) if you'd like to give it a go.

I'll update this issue when we have more information to share about new features.

**Comment by PuneetKohli** [comment]
I agree with your idea of having them as opt-in features. Thanks for sharing the contributing guidelines, will definitely see if I (or a co-worker) would be interested to contribute alongside our full-time roles.

Thanks!

**Comment by rachellerathbone** [comment]
Hi @PuneetKohli. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by ccrolf** [comment]
Hi, have you tried to use [Automation](https://www.atlassian.com/software/jira/features/automation) to accomplish the same effects? This is a far more powerful mechanism that workflow triggers and the preferred mechanism for DevOps automation.

**Comment by rachellerathbone** [comment]
Hey @PuneetKohli. As we haven’t heard from you in a while, I’m going to go ahead and close this issue. Please feel free to reopen if you still require assistance.
