### ISSUE TITLE
Link In JIRA Ticket

### ISSUE THREAD

**Issue by sriley-ciena** [atlassian/github-for-jira#1357]
Hello 
Quick question how can we add a link in the JIRA ticket for GIT Hub? We see one for BITbucket but can we get one for Github and if so how?

**Comment by rachellerathbone** [comment]
Hey @sriley-ciena. Can you provide a little more context? Perhaps a screenshot of the link you'd like to see in Jira?

**Comment by rachellerathbone** [comment]
Hey @sriley-ciena. As we haven’t heard from you in almost 2 months, I’m going to go ahead and close this issue. Please feel free to reopen if you still need assistance.
