### ISSUE TITLE
Unable to integrate Jira Cloud with Github Organization

### ISSUE THREAD

**Issue by servicerocketal** [atlassian/github-for-jira#1378]
Hello team,

We are trying to integrate Jira Cloud and Github using the KB below:-

- https://support.atlassian.com/jira-cloud-administration/docs/integrate-with-github/

Upon reaching step 4, the Organization that we are trying to select has the below error message:-

- This Organization's IP address is blocked. Learn more

As highlighted in the KB, we have already white-listed 13.52.5.96 through 13.52.5.111. Are there still other IP that needs to be white-listed?

Regards.

**Comment by Ritma-Teknoloji** [comment]
i didn't be able to integrate too

**Comment by yersoy** [comment]
mee too its not working.

**Comment by mboudreau** [comment]
Could you try follow the simple method here: https://github.com/atlassian/github-for-jira/blob/main/docs/ip-allowlist.md#simple-method

Thanks

**Comment by servicerocketal** [comment]
Hello @mboudreau ,

We have already verified that both boxes are checked.

We are still receiving the below error message:-

- This Organization's IP address is blocked. Learn more

Regards.

**Comment by chriskl** [comment]
Hi,

My org also has the same problem.  We have used the simple method and I can confirm that it has enumerated automatically every separate IP into the allowlist.  Still receiving the message that the IP is blocked when trying to set up the connection from the Jira side.  Our org uses Enterprise Managed Users.

Chris

**Comment by YugoHino** [comment]
Hi,

Same as us. App configuration looks finished, but it's still not working. We cannot see the org on the tool chain section in the project. Also it's failed to fetch the branches on the section of Create GitHub Branch. 

App configuration
![image](https://user-images.githubusercontent.com/26473682/207776192-bc4ed268-5e2a-4854-8c55-00b903ee569f.png)

The tool chain section
![image](https://user-images.githubusercontent.com/26473682/207776623-7b5a4728-d24c-484d-9016-87fe6984c87a.png)

The section of Create GitHub Branch
![image](https://user-images.githubusercontent.com/26473682/207776765-50a61894-4c66-4724-983a-c0335aed8999.png)

Thank you for the investigation.

**Comment by bgvozdev** [comment]
@YugoHino we recently fixed some bugs with create branch functionality, please report remaining problems (if you still have them) here: https://github.com/atlassian/github-for-jira/issues/1845

For the rest folks: we recently fixed a bug related to IP whitelisting. I'm closing this off but please feel to open a new issue if you are still experiencing troubles! Thank you.
