### ISSUE TITLE
It is possible to connect an organisation for which GH user don't have an admin access

### ISSUE THREAD

**Issue by KAbakumovAtl** [atlassian/github-for-jira#139]
While connecting my GitHub account to Jira I can see the following options when choosing organisations to connect:
![gh_orgs](https://user-images.githubusercontent.com/42425541/46382206-5925d300-c6ed-11e8-8439-a12fefea3e59.jpg)

As discussed on the meeting I should not see the "integrations" organisation, because I don't have an admin access to it.

**Comment by rachellerathbone** [comment]
![Screen Shot 2021-05-17 at 3 57 53 pm](https://user-images.githubusercontent.com/37155488/118439130-b947d700-b728-11eb-8fb0-f6820da95bcf.png)

Looks like orgs that a user doesn't have admin access to are still listed. I've flagged this with 'to-triage' for my team discuss this issue.

**Comment by rachellerathbone** [comment]
Closing this issue. A UX decision determined we should include all orgs otherwise customers may become confused that they can't see an org at all. This explicitly informs them they can't connect to certain orgs.
