### ISSUE TITLE
Could not see any Github configuration 

### ISSUE THREAD

**Issue by argentra-kumar** [atlassian/github-for-jira#1416]
Dear Team,

I have app "GitHub for Jira" in the cloud. but could not see any configuration menu  to connect to Github. Is there any issue with this app?. Please advise to solve the issue. I have attached the screenshot for your reference.

thanks
![image](https://user-images.githubusercontent.com/17444546/181143943-f1ece25a-dea6-4df6-8eae-de3943454875.png)

**Comment by mboudreau** [comment]
Install the app and then it should appear under the "Apps" top menu under "Manage Apps".  It should show in the side bar.  If any of these options are missing, then you do not currently hold the permission to install or manage apps within this Jira instance.  You should speak to the admin.

**Comment by argentra-kumar** [comment]
Dear mboudreau

Thanks for the response. Let me check with our team. thanks
