### ISSUE TITLE
Backfill Status delay/stuck?

### ISSUE THREAD

**Issue by ChrisFerrett** [atlassian/github-for-jira#1454]
At around 15:00 BST yesterday (02/08) we started the backfill for our repos. Granted we have a lot of them (235) but the sync got to repo 19 and has been at the same state for the past 24 hours.

Is there a possibility that the backfill has got stuck? How long should we wait?

![image](https://user-images.githubusercontent.com/108929936/182626745-51967d71-97ce-4235-8112-d86664c5bec5.png)

**Comment by mboudreau** [comment]
Could you please try to restart the backfill?  Also, please provide us with your jira domain and we'll check our logs, thanks!

**Comment by rachellerathbone** [comment]
Hey @ChrisFerrett. Please let us know if you still require assistance with this.

**Comment by rachellerathbone** [comment]
Hey @ChrisFerrett. As we haven’t heard from you in almost 2 months, I’m going to go ahead and close this issue. Please feel free to reopen if you still need assistance.
