### ISSUE TITLE
Github admin and Jira admin are separate entities and don't have admin access on both github and jira. What to do?

### ISSUE THREAD

**Issue by gryz** [atlassian/github-for-jira#1466]
We have an enterprise cloud github that is owned and run by a client. They don't allow outsiders to be org admins. They made a separate org for this project if that matters.

We have our jira cloud project(s) that we want to connect to the various repos. We manage the jira cloud instance and cannot give the github admin, admin access to our jira system.

Any ideas on how to do this?

**Comment by rachellerathbone** [comment]
Hey @gryz. Unfortunately, I don't think there is anything that can be done. When you install the GitHub for Jira app and try to connect to an organisation in GitHub, the app goes through an auth flow where it attempts to verify that the user has access to the account/org. If they don't, a connection cannot be made. Someone who is an admin in Jira would also need to be an admin in GitHub.
