### ISSUE TITLE
Support JIRA project keys with numbers

### ISSUE THREAD

**Issue by isaacbrodsky** [atlassian/github-for-jira#1481]
In https://github.com/atlassian/github-for-jira/blob/3fc245d27a3be83174f15147e9e2005bf2a0c2d0/src/util/jira-utils.ts#L88 project IDs that have numbers, such as `ABC1`, will not match. E.g. the ticket key `[ABC1-1]` will not work. These are valid project keys in JIRA so the regex should detect them.

**Comment by rachellerathbone** [comment]
Hey @isaacbrodsky. Good callout. Let me create an issue in our backlog to update our issueKeyParser util to include this issue key format.

**Comment by mboudreau** [comment]
This has been fixed.
