### ISSUE TITLE
How do I restrict which Jira Cloud Projects can use the GitHub Connector

### ISSUE THREAD

**Issue by HockeyFanRA** [atlassian/github-for-jira#1502]
Not all Jira projects are using GitHub as the source code repository.  I need to eliminate the GitHub information from showing within Jira Cloud projects not using GitHub.

**Comment by bgvozdev** [comment]
Hey @HockeyFanRA , the linking of GitHub data to Jira issues is happening by the mentioning of Jira issue keys in commit messages, branches, PR titles etc. If you don't want to have you GitHub data linked to a specific project, all you need to do is to avoid using issue keys in the aforementioned places when using git/GitHub. 

"GitHub for Jira" app doesn't have such feature as to enable/disable GitHub data for a specific project per se. The integration works on the level between the whole Jira and a GitHub org.

Please feel free to reopen the issue
