### ISSUE TITLE
Is it possible to access GitHub PRs made before External System Import along with those made after?

### ISSUE THREAD

**Issue by SLPeterRose** [atlassian/github-for-jira#1517]
Hi. Looking to migrate a SW Dev Team to Jira from another tool and see historic and Jira referenced commits merged. Is this possible?

Info: we have copied the GitHub references from the old tool into Jira's External Issue ID field hoping that Jira would recognize as an imported issue and manage the bookkeeping. Looks like it doesn't work for us out of the box.

Is it possible to see the historical GitHub info merged with Jira integrated? Any insight as to how we can make this work?

Cheers.

**Comment by thombergs** [comment]
Hey @SLPeterRose,

when you initially connect the GitHub for Jira app to your GitHub org, it scans all commits, branches, pull requests, builds and deployments from your GitHub repos for Jira issue keys. If there is a Jira issue key in a commit message, branch name, or pull request description, that commit, branch or pullrequest will be added to the issue in Jira.

If you haven't used Jira issue keys in your historical GitHub commits, branches, etc, then the integration won't find the historical data and it won't be visible in Jira.

We don't support Jira's "External Issue ID" field, sorry. But I'm curious: what exactly did you copy into that field?

Cheers,
Tom

**Comment by SLPeterRose** [comment]
Thanks Tom.

Sorry to hear that you don’t support historical commits for Imported issues.

FYI… “External Issue ID” has the GitHub ‘Issue Key’ we were hoping you would use to associate the new Jira issue with our legacy tracking system. So PRs, for example would be sync’d with Jira Issue Key (e.g. JIRA-100) OR External Issue ID (e.g. “AA-200” from our Legacy tracking system).

Now after moving a large team to Jira, engineers will need to go back to the old issue tracker for GitHub history. We were hoping we could keep them in Jira and turn the old tracker off. Does the use case make sense?

Cheers,
Peter

From: Tom Hombergs ***@***.***>
Date: Wednesday, August 24, 2022 at 9:50 PM
To: atlassian/github-for-jira ***@***.***>
Cc: SLPeterRose ***@***.***>, Mention ***@***.***>
Subject: Re: [atlassian/github-for-jira] Is it possible to access GitHub PRs made before External System Import along with those made after? (Issue #1517)

Hey @SLPeterRose<https://www.google.com/url?q=https://github.com/SLPeterRose&source=gmail-imap&ust=1662007810000000&usg=AOvVaw3xQAq8MjqYEbOelf8zBQAY>,

when you initially connect the GitHub for Jira app to your GitHub org, it scans all commits, branches, pull requests, builds and deployments from your GitHub repos for Jira issue keys. If there is a Jira issue key in a commit message, branch name, or pull request description, that commit, branch or pullrequest will be added to the issue in Jira.

If you haven't used Jira issue keys in your historical GitHub commits, branches, etc, then the integration won't find the historical data and it won't be visible in Jira.

We don't support Jira's "External Issue ID" field, sorry. But I'm curious: what exactly did you copy into that field?

Cheers,
Tom
