### ISSUE TITLE
Error Rendering on Jira Card view 

### ISSUE THREAD

**Issue by RandiRogersBP** [atlassian/github-for-jira#1550]
We started seeing this issue last night. 
When you are on the Kandan/Card view in jira an error appears on the card. However when you click into to card all of the expected information from git is visable. 
I have completed a Connection refresh and a Backfill. 
Error: 
![SCR-20220825-h4u](https://user-images.githubusercontent.com/97688190/186730295-bf9e2d7e-68f9-43e0-876a-683a15b25ef1.png)

In ticket: 
![SCR-20220825-h9w](https://user-images.githubusercontent.com/97688190/186730694-f756e0c9-e209-49aa-99c1-8f75f9c26950.png)
![SCR-20220825-ham](https://user-images.githubusercontent.com/97688190/186730698-a26b250a-4c8e-4243-90bb-c92f716d0303.png)

**Comment by rachellerathbone** [comment]
Hey @RandiRogersBP. Unfortunately, this isn't owned by our team. Let me reach out to some other folks to see if I can find out which team does own this component.

**Comment by RandiRogersBP** [comment]
Closing this out. This issue was sloved by Jira support, seems to have been casued by an internal issue on their end.
