### ISSUE TITLE
Change product URL

### ISSUE THREAD

**Issue by justindiiorio** [atlassian/github-for-jira#1554]
We are planning to change the product URL on our Atlassian cloud instance. Is there an impact/change that needs to be planned/managed for the Github for Jira plugin?

**Comment by mboudreau** [comment]
Hm, yes, I believe there would be.  You'd need to re-add Github for Jira, configure it as before and sync the data again.

Cheers.

**Comment by ssexton1323** [comment]
@justindiiorio  - We are also looking to update our URL - would you possibly be able to update if you did have to re-add and configure Github for jira once the url change was performed?   thanks!

**Comment by justindiiorio** [comment]
@ssexton1323 it was pretty straight forward, no need to reinstall the add on. Following the URL change, we reconnected to the GitHub org and ran the sync. Took just a few minutes in all. The only down time for users is the time  between the URL change and the reconnect.

**Comment by ssexton1323** [comment]
great - thank you very much for the update - appreciate it!
