### ISSUE TITLE
Need help evaluate github-for-jira app - security

### ISSUE THREAD

**Issue by iheitmann** [atlassian/github-for-jira#1592]
For a client of ours, I am currently helping them in evaluating github-for-jira in regards to data security. I see several questions etc here discussing security from jira into Github. However, what my customer is questioning is data security the other way, meaning from github into Jira. 

To summarise:
* who will be the actor of commits etc? the actual user or a github-for-jira-user?
* what Jira data will be accessible for users in GitHub?
* does the app follow standard Jira permissions, meaning that if github user does not have read-permission in projects, he/she will not be able to see content either

I´m not a developer myself, so I´m not to familiar with using GitHub itself

**Comment by thombergs** [comment]
Hey @iheitmann, 

I have recently added this [security FAQ](https://github.com/atlassian/github-for-jira/blob/main/docs/security.md) to our docs. Please have a read through this and feel free to re-open this issue if you still have some questions (and we may add them to the FAQ).

Cheers,
Tom

**Comment by iheitmann** [comment]
Hi @thombergs .
Thanks. And just to be sure I understand - am I correct in understanding that Github users in fact cannot see/search for issues in Jira at all? Meaning: they would have to have direct access in JIra in order to find correct issue key first, then add it to commits etc in github? There is no search for issues option within Github?
