### ISSUE TITLE
Server to Cloud migration help

### ISSUE THREAD

**Issue by akhilpersonal** [atlassian/github-for-jira#1598]
Using DVCS account to link Github in server Jira . 
Planning to migrate Jira to Atlassian cloud. 
Question : Once data migrated to Atlassian cloud , then by installing GitHub for Jira app , all existing integrations shows in cloud as well (eg: linked commits , branches etc) ? or is there a data lose ?

**Comment by mboudreau** [comment]
That's correct, the old DVCS data isn't migrated over, but once you add the Github for Jira plugin and set it up, it'll get all related content from Github and associate it with the appropriate ticket the same as DVCS did.  No "data loss".

Please try it out and let us know how you go.
