### ISSUE TITLE
Can you please let us know what is the best approach to setup App password for Jira Integration.

### ISSUE THREAD

**Issue by raghunathreddypalla** [atlassian/github-for-jira#1602]
Can you please let us know what is the best approach to setup App password for Jira Integration.
Original request was to add github plugin to our Sportsnet Board.

**Comment by raghunathreddypalla** [comment]
Hi Team,
Can you please provide an update with the above ask.

**Comment by mboudreau** [comment]
I'm not sure I follow, what do you mean by App password?

**Comment by raghunathreddypalla** [comment]
Hi Michael,

Our original request was to add a github plugin to our Sportsnet Board (https://reqcentral.com/secure/RapidBoard.jspa?rapidView=4208&projectKey=SNNGAP&view=planning.nodetail&issueLimit=100<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Freqcentral.com%2Fsecure%2FRapidBoard.jspa%3FrapidView%3D4208%26projectKey%3DSNNGAP%26view%3Dplanning.nodetail%26issueLimit%3D100&data=05%7C01%7CServ_Helpdesk%40rci.rogers.com%7C40865fea8c4349ca94f208da7af159c3%7C0ab4cbbf4bc74826b52ca14fed5286b9%7C0%7C0%7C637957474246916143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oT05sAzALS85Osytlt4wuC%2FYBPTCBHgvAGy3evMNCJI%3D&reserved=0>)
 Here is the github plugin I'm hoping to connect:
 https://marketplace.atlassian.com/apps/1219592/github-for-jira?hosting=cloud&tab=overview


Can you please let us know what is the best way to setup Application password for JIRA integration? So application team can access using 2MFA.

I guess it might be in oAuth Apps (under dev settings) but just wanted to confirm with you.

Regards,
Raghunath

**Comment by raghunathreddypalla** [comment]
Hi Michael,

We are unable to login Github ID and password with admin account and some other team has admin access.
 Can you please provide steps on how to configure plugin.


Our original request was to add a github plugin to our Sportsnet Board 
Here is the github plugin I'm hoping to connect:
 https://marketplace.atlassian.com/apps/1219592/github-for-jira?hosting=cloud&tab=overview

**Comment by rdmsupport** [comment]
Since we are integrating Github plugin to Jira sportsnet board, we need to setup ID and password for different team and need to setup 2MFA authentication for the application team to login.
We need to know how we can setup ID and password for different application and use 2MFA authentication.

**Comment by mboudreau** [comment]
I think you need to bring this up with Jira support directly.  The Github for Jira app doesn't handle any kind of authentication directly - there's the Jira specific authentication, then there's the Github authentication, both of which we don't directly affect but are just a middleman between both.

Cheers.
