### ISSUE TITLE
Backfill Status appears to be stuck

### ISSUE THREAD

**Issue by rfriedel** [atlassian/github-for-jira#1604]
We have connected 4 GitHub organizations to our Atlassian instance `jciproducts.atlassian.net`. 3 of the GitHub organizations synced all the way, one of them keeps getting stuck.  I started a new Backfill 24hrs ago and got stuck again at 406/730. We had reached over 500 in a prior attempt.
Could you please advice how to proceed? I have no visibility (or knowledge?) how to debug this. :(
Thank you, -Rudi.

**Comment by mboudreau** [comment]
Hm, interesting.  We seem to be getting a 500 error from the Github API when trying to get pulls from a specific repository.  Could you open a support ticket with Github and provide them with this Github Request ID `4C90:6EB6:106D56B:10E30C9:632334FD` for them to reference.  

Thanks

**Comment by rfriedel** [comment]
@mboudreau - thank you for looking into that. I created support ticket `1801185` with your reference. Thank you.

**Comment by rachellerathbone** [comment]
hEY @rfriedel. Thanks for opening that support ticket with GH. I'm going to go ahead and close this issue as I don't believe there is anything else we can do on our end. If you do need more assistance from us, however, please feel free to reopen.
