### ISSUE TITLE
Getting PR comments

### ISSUE THREAD

**Issue by calloquy-dusty-fowler** [atlassian/github-for-jira#1618]
Hello, with this integration is it possible to get the comments attached to a pull request?  I see it mentions comments for commits, but was hopeful to get PR's.  This way QA or business leaders can see within the JIRA ticket itself if PR's are being reiterated upon.  Simply adding as a comment on the ticket with some sort of call-out that it relates to the PR would be fantastic!  Thanks!

**Comment by rachellerathbone** [comment]
Hey @calloquy-dusty-fowler. A PR was recently merged by one of our team members that should address this issue for you so I'm going to go ahead and close this. Please feel free to reopen if you need further assistance.
