### ISSUE TITLE
Backfill marked as complete, but some tickets in Jira Cloud show no commits.

### ISSUE THREAD

**Issue by rpopp-fni-stl-com** [atlassian/github-for-jira#1644]
Good morning,

As the title suggests, we seem to have an issue where some commits are not showing up for a ticket, even though backfill is marked complete for our organization.  This is in our new Jira cloud instance.  The odd thing is, our older on-prem Jira system DOES show the commit, branch, et al.

Is there a way to reinitiate a backfill process for a specific repository, or maybe a log location for the backfill to check if there was some processing error?

TIA
Reuben

**Comment by atrigueiro** [comment]
Hi @rpopp-fni-stl-com,
I'm happy to have a look at our logs for you.
What's your Jira cloud instance name?

Thanks.

**Comment by rachellerathbone** [comment]
Hey @rpopp-fni-stl-com. As it's been almost a month since we've heard from you, I'm going to go ahead and close this issue. If you still require our assistance, please feel free to reopen and send your Jira cloud instance name through so we can dig through our logs.
