### ISSUE TITLE
GitHub development data migrate from server to cloud app.

### ISSUE THREAD

**Issue by harishtc** [atlassian/github-for-jira#1680]
Hi Team,

Recently we have done Jira migration from server to cloud.
after migration, we have observed that git development data has not been migrated from server to cloud. we are using GitHub for Jira addon for integration.
is there any possibilities to migrate the data now.

Regards,
Harish.
![Git Dev data](https://user-images.githubusercontent.com/97159597/196234255-fac0e33d-dc32-4cf6-9eac-9668f5bd1ebf.JPG)

**Comment by mboudreau** [comment]
I'm not sure what you're asking? You just need to restart the backfill to get your data back as the app data doesn't transfer.  Any other question you have, I'd suggest you bring it up with Jira support.
