### ISSUE TITLE
How to update labels in deployment tab.

### ISSUE THREAD

**Issue by uvarma** [atlassian/github-for-jira#1709]
![Dev](https://user-images.githubusercontent.com/116684906/197883046-c235c13c-d697-4e0e-9863-bee2549a3e22.png)
Need to change the "Others" label to "QA" in the deployments tab. Please help us with how to change this.

Thank you.

**Comment by uvarma** [comment]
Hi There,
Can we have an update on this?

**Comment by benoittgt** [comment]
Hello

You should check https://github.com/atlassian/github-for-jira/issues/1536 as it is related.

At the moment other env are not handled. See documentation: https://github.com/atlassian/github-for-jira/blob/main/docs/deployments.md#environment-mapping

**Comment by mboudreau** [comment]
@uvarma Benoit is right, we're currently limited by what Jira can handle and sandly, those environment names are limited to what's here: https://github.com/atlassian/github-for-jira/blob/main/docs/deployments.md#environment-mapping

The closest one we have currently is "testing".  Follow the documentation above to know how you can map it.

I'm going to close this ticket as it's a duplicate.
