### ISSUE TITLE
Unable to link a new repository to jira.

### ISSUE THREAD

**Issue by daniel9917** [atlassian/github-for-jira#1712]
When I try to add a new repository, the option to select the repository is disabled.
![image](https://user-images.githubusercontent.com/30665710/198190447-e15a4dbc-6874-4fbc-a6ed-61ecbd78ff71.png)
![image](https://user-images.githubusercontent.com/30665710/198190525-90f26764-d65c-44d8-884d-312369d14660.png)
When I hit the only available option which is Grant access to your github workspaces, I can manage the repositories I want jira to see.
![image](https://user-images.githubusercontent.com/30665710/198190703-9e84ed50-5a93-4dc0-8af7-ca937cc08b96.png)
After I manage those settings, i go back to add the repository and the select for the repo is still disabled. Is there anything Im missing? Tx in advance

**Comment by mboudreau** [comment]
Hm, that seems to be a broken UX on the Jira side since you can't "add" a repository for a Github repo to Jira.  Everything's done based on the repositories you give access to and if there's data that's been associated with a Jira ticket with that repository in it.  The repository missing will show up once an issue key is added to a commit, branch, pr or build

**Comment by mboudreau** [comment]
@daniel9917 Wait, are you using the Github for Jira app or is this the Github Oauth Integration?

**Comment by rachellerathbone** [comment]
As we haven't had a response in a couple of months, I'm going to go ahead and close this issue. If you need further assistance, please feel free to reopen.

**Comment by sergio-ivanuzzo** [comment]
@rachellerathbone I have similar issue. I have one organization and previously I added a repo from it to my board. Recently I created new board for same organization and tried to link another project from it. But however I changed organization settings, github for jira still shows 1 project in the list.

Could you clarify how to fix this ?
