### ISSUE TITLE
Support for Tags

### ISSUE THREAD

**Issue by raj-m7** [atlassian/github-for-jira#1719]
Dear Team,

By any chance, do you have plans to extend your plugin with the support for Tags? The current plugin is helping us pretty well but the only missing feature is Tags. Could you please get this feature request implemented in the near future? Please do let me know the request status, if this can be accepted or not. 

Thanks in advance for your support. 

Regards,

Raj

**Comment by rachellerathbone** [comment]
Hey @raj-m7. We have another issue #147 open for this feature request. Our team does have a ticket for this in our backlog and hope to address it. Unfortunately, I can't give you a timeline for this as the team is busy working on other features that have higher customer demand/impact. 

As this is a duplicate issue of 147, I'm going to go ahead and close this issue. Please react to the existing thread and keep your eye on that one.
