### ISSUE TITLE
"Jira Host url is missing" on connecting Jira project to github organisation

### ISSUE THREAD

**Issue by YShane** [atlassian/github-for-jira#1767]
There appear to be a few similar tickets opened but with no actual resolution to any of them, I've decided to open another. 
Trying to link a github account/org to a jira installation results in a simple "Jira Host url is missing" message. I've tried all sorts - including uninstalling and then reinstalling the github plugin, with no luck. 

I'm now going to pursue the github side setup as a few other ticket creators have suggested in other (now closed) tickets. Please have a look at this - it's shocking that such basic functionality doesn't appear to work.
![image](https://user-images.githubusercontent.com/21192296/204136038-e5bfaf6e-f402-4e81-bc64-429c5c8f44f4.png)

**Comment by klappradla** [comment]
Same problem here. Could you link to other issues reporting and then eventually solving this in a different way @YShane? I could not find anything useful for my particular situation: I cannot reinstall the connection on the Github side, because my organization is already connected to some other Jiras where I personally don't have access. So I cannot break and recreate that connection there.

**Comment by SylvainNConnect** [comment]
I just have the same issue.

**Comment by klappradla** [comment]
> @klappradla, haven't been able to find anything myself, sorry. Have you?

I gave it another try today and was able to successfully connect, yes 🎉

Here's what I did: I used a different browser (Chrome while Firefox is my default) where I'm not logged into GitHub. I had a slight suspicion that GitHub's 2FA and my existing session somehow messed up the flow of redirects. So with the completely fresh browser and the new logins (when prompted) there, it actually worked.

If you're depending on the integration, maybe give this approach a try.

**Comment by YShane** [comment]
This appears to have been fixed now so closing :). I'm however somewhat skeptical as I initiated the connection on a mac device this time. It's entirely possible this still doesn't work from a windows machine.

**Comment by kegi** [comment]
Not fixed. Look like a Firefox bug

**Comment by hlosukwakha** [comment]
I'm getting this on Chrome too

**Comment by klappradla** [comment]
> Not fixed. Look like a Firefox bug
> […]
> I'm getting this on Chrome too

As said, I think for me this did not have anything to do with the browser or browser vendor itself. I only reached out for my non-default browser in order to not have any cookies set.
