### ISSUE TITLE
Can no longer reconfigure Jira for Github app after changing Jira URL

### ISSUE THREAD

**Issue by kma-veza** [atlassian/github-for-jira#1783]
<img width="398" alt="Screen Shot 2022-12-07 at 5 43 28 PM" src="https://user-images.githubusercontent.com/108376445/206338092-f7ce8b24-a2cf-406e-8d9a-b72e59e3c4fa.png">

Hi, we changed our product URLs for our Atlassian products and the integration stopped working. From a past issue, I see that the recommendation was to reconfigure the app to the Github org, but the app itself is not loading now on Jira. What would be the recommendation from here?

**Comment by mboudreau** [comment]
Hi @kma-veza, this is "normal" as we use the jira instance url as a key.  You'll need to uninstall the app and reinstall it, then it'll backfill back the data into your jira instance.  This will not lose any data, but it might be unavailable for a few hours depending on how large your organization is.

I'll close this ticket unless you get another issue, thanks.

**Comment by dhirennotani19** [comment]
Hi @kma-veza ,

I am Dhiren Notani, one of the Pre-Sales Engineers working at Exalate.
Can you please confirm if you are using 'GitHub for Jira' App which is provided by Atlassian or some other app by some other vendor?

By any chance are you looking for an integration tool for GitHub <-> Jira integration?

[Exalate](https://marketplace.atlassian.com/apps/1213645/exalate-jira-issue-sync-more?hosting=cloud&tab=overview), provides a fully bi-directional synchronization between ServiceNow, GitHub and Jira (among other ITSM systems) that is fully customizable. It is easy to set up and Exalate uses a scripting engine which is based on Groovy scripts where you can control what data you want to share and even you can independently handle the incoming information. You can achieve complex use-cases with ease.

Feel free to book a [demo](https://exalate.com/book-demo/) with us if you want to discuss this in more detail and want to learn more about the capabilities of the tool.

Thanks
Dhiren
