### ISSUE TITLE
Username missing from PR's

### ISSUE THREAD

**Issue by TopHatCroat** [atlassian/github-for-jira#1790]
Hi,

here is a picture to describe the issue.
<img width="467" alt="Screenshot 2022-12-12 at 09 40 49" src="https://user-images.githubusercontent.com/9058532/207000051-40e7c791-3932-4c76-81c9-8bfd928eb5bc.png">

Basically what's happening is that it's showing the correct number of reviewers but it's not showing their user name and picture.
This issue started happening somewhere around the start of the last week.
I've tried removing and readding the plugin, it has permissions for the entire organisation from GitHub's side as seen here:

<img width="730" alt="Screenshot 2022-12-12 at 09 45 12" src="https://user-images.githubusercontent.com/9058532/207000790-ed86632c-0b27-469e-8b59-c53a7e836a8b.png">

And this is how it looks on Jira Cloud
<img width="970" alt="Screenshot 2022-12-12 at 09 51 56" src="https://user-images.githubusercontent.com/9058532/207002145-83db553c-43d4-4201-b741-fda938b2995b.png">

Any ideas on what could be the cause of this?
Thank you in advance

**Comment by atrigueiro** [comment]
Hi @TopHatCroat,

As mentioned [here](https://github.com/atlassian/github-for-jira/blob/main/docs/FAQs.md#q-why-cant-i-see-the-author-reviewer-names-andor-icons-in-my-jira), in order for the author, reviewer names, and/or icons to appear in the development panel of your Jira issue, the email address associated with your GitHub account should match the address in your Jira account. If these two email addresses are different, then the account names and icons will not show up in Jira. This behavior is similar to smart commits, which also require matching emails.

Cheers,
Amanda.

**Comment by bmacinanti** [comment]
@atrigueiro Hi, Amanda. 
This doesn't make much sense to me and I'm sure others. People had github accounts long before they signed up for these atlassian accounts and we have company email addresses assigned. Are we expecting people to update their github account emails every time they switch atlassian spaces/jobs? That's not ideal. This should be re-examined I think. Thank you for your time.

**Comment by TopHatCroat** [comment]
@atrigueiro Sorry for my late response. This makes sense, but this feature worked 2 weeks ago, so it just stopped at some point and hence the issue I opened.
I assumed this would also be able to see emails listed in the associated emails on a GH profile?
