### ISSUE TITLE
Search of repository doesn't work when trying to create a branch from a Jira ticket

### ISSUE THREAD

**Issue by RoyLeibo** [atlassian/github-for-jira#1791]
Hi,

We have integrated GitHub with Jira.
When clicking on create a branch in the Jira ticket, I am being redirected to GitHub.
Then, I am trying to search for the repository that I wish to open the branch in under our organization but the search doesn't work, load spinner works infinitely.
When I am accessing the list I can find the repo manually and it works.

Is there an issue with the repository search?

Thanks!

**Comment by atrigueiro** [comment]
Hi @RoyLeibo,

Thanks so much for reporting. I was able to replicate the issue.
I'll add it to our backlog and we'll try to get a fix out as soon as we can.

Will keep this issue updated.

Cheers,
Amanda.

**Comment by mboudreau** [comment]
@RoyLeibo Yes, but no.  The repository search works, but only for Repositories that Jira already know about.  The problem is that Jira, at the moment, doesn't accept github data that doesn't have a jira issue key.  We're aware of this problem and working towards making this a reality.

**Comment by imirandad** [comment]
:( is there a work around for this issue so we can connect jira with our repositories? 

<img width="658" alt="image" src="https://user-images.githubusercontent.com/107424820/215621630-b2c991d7-750f-4623-ace2-b7f56cfd9607.png">

**Comment by bgvozdev** [comment]
Hey all, we fixed a bunch of issues with the feature just recently. It is tracked here https://github.com/atlassian/github-for-jira/issues/1845 . If you still experience issues, please report there instead. Thank you!
