### ISSUE TITLE
Create a branch from a branch including a '/' character fails

### ISSUE THREAD

**Issue by jbparker** [atlassian/github-for-jira#1798]
When using the `Create branch in GitHub` functionality, a branch cannot be used as a base if it includes the '/' character, even when selecting an item in the list.

It fails with the message: _**Could not find this branch on GitHub.**_

It appears that problem lies below: https://github.com/atlassian/github-for-jira/blob/d4e1561cc6e431f8ccd5ae2d1119b8bfb9d71526/static/js/github-create-branch.js#L114

Since `${branchName}` is not URL encoded, the call fails with the message **_Cannot GET /github/branch/owner/{org_name}/repo/{repo_name}/{branch_name_including_slash}_**.

As expected, manually URL encoding the branch name works and allows the branch to be created.

**Comment by mboudreau** [comment]
Yep, that's a very good find, should be an easy enough fix.   Gimme a moment.

**Comment by mboudreau** [comment]
@jbparker sorry, forgot to mention this went out yesterday to production and should fix your use case.  I'll close the ticket for now unless there's something else.  cheers.

**Comment by jbparker** [comment]
@mboudreau awesome, thanks! Just verified it fixed on our end. Appreciate the blazing turnaround!
