### ISSUE TITLE
Reverse Proxy Support

### ISSUE THREAD

**Issue by shineArg** [atlassian/github-for-jira#1810]
Hiya,

Documentation (and Atlassian Support) state that **Reverse Proxies** are not supported for using github-for-jira with a self-hosted GHE. Is there any (even partial) workaround? Will they/can they be supported in the future? Example use would be to allow-list only the routes required for the app to function.

Thanks!

**Comment by mboudreau** [comment]
@shineArg Hi!
That's correct, reverse proxies are not supported at the moment, but we have talked about them and I'm personally pushing for it for our GHE customers as the best way to keep things secure between cloud and your personal network.  At the moment you have to punch a hole in your firewall to allow us access to your GHE instance.

Giving a whitelist of routes we hit is not a sustainable solution as we are constantly changing or adding new functionality which means you'll have to maintain this whitelist.  A possible workaround is to use something like AWS API Gateway or an nginx server and essentially creating your own secure proxy and then just change the URL to your GHE server to point to the proxy instead.

**Comment by kerrhome** [comment]
We would really like to see this supported.  Is there any ETA for this?

**Comment by bgvozdev** [comment]
Hey @kerrhome , we are actively working on this feature right now, and actually we already have support of API keys (a custom header injected in all requests to a GHE). Unfortunately, UI is not ready yet, however if you are eager to try it early please reach out our support https://support.atlassian.com/contact/ and we could help you there. Thanks!

**Comment by bgvozdev** [comment]
Hey @shineArg  @kerrhome , the feature has been implemented and available to everyone. Please refer to these docs: https://support.atlassian.com/jira-cloud-administration/docs/connect-a-github-enterprise-server-account-to-jira-software/#API-key-based-pre-authorization 

Closing the issue.
