### ISSUE TITLE
Time Localization

### ISSUE THREAD

**Issue by sum1275** [atlassian/github-for-jira#1813]
My team is using Jira for Development and Testing team  task  management. But  the  timestamp is UTC rather than IST creating a confusion among the development and Testing team.
![image](https://user-images.githubusercontent.com/59500999/209763203-e87e03ae-1854-4c14-aae0-1a520aec7dcf.png)

**Comment by rachellerathbone** [comment]
Hi @sum1275. Thanks for reaching out. Unfortunately, this is owned by another team at Atlassian so we are unable to help with this request. Please open a support ticket with [Jira Software](https://support.atlassian.com/jira-software-cloud/) so you can be directed to the correct team.

**Comment by sum1275** [comment]
May you redirect me to the team on which I have to mention the issue

**Comment by rachellerathbone** [comment]
I'm not sure which team owns it. Once you open a support ticket, support staff will be able to direct you to the correct team.

**Comment by UnresolvedCold** [comment]
@sum1275 
Similar issue was reported on Atlassian Community - https://community.atlassian.com/t5/Jira-Software-questions/Issue-with-time-zones/qaq-p/1070038
