### ISSUE TITLE
Draft pull requests trigger "Pull request created"

### ISSUE THREAD

**Issue by dpraul** [atlassian/github-for-jira#182]
I understand that Draft pull requests are a fairly new feature, so maybe it's just that the workflow hasn't been entirely ironed out with how they work with the Jira integration. 

That said, opening the discussion: I'm not sure if a draft pull request makes sense to trigger "Pull request created". Right now we use that trigger to transition issues from "In Progress" to "In Review", and I think the [intent of a draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/#tag-your-work-in-progress) is to signal code is still being developed, thus why it also does not trigger `CODEOWNERS`. I'm also open to suggestions on how to do the transition better if it sounds like I'm in the wrong ballpark.

Thanks!

**Comment by tcbyrd** [comment]
Hey @dpraul Thanks for opening this issue! Definitely makes sense to discuss how this should work here. One dependency we have is that the enum for the Pull Request status is this:

https://github.com/integrations/jira/blob/c2b329dd200c3dd348104a16f442602067644fc7/docs/DevInfoAPI.json#L427

It would be great if Jira had a "Draft" state, and maybe we can talk to Atlassian about adding that to their API, but in the mean time, would you rather not have the Pull Request be sent to Jira at all if it's in Draft state? I feel like this could be something people have different opinions on. Personally I would say that creating a Pull Request doesn't necessarily mean it's in review, and maybe you could update the PR title to include the transition syntax when it's really ready for review?

**Comment by dpraul** [comment]
I agree with your point on people having differing opinions - I'm not certain leaving draft pull requests out of Jira is the best solution.

Definitely also see your point on a PR opened not necessarily meaning it's in review (my workflow configuration skills are weak, so I'm sure there is room for improvement there). Ideally the workflow would be able to pick up when reviewers are added to a PR and use that to fire the transition, but I haven't had a chance yet to figure out if I can do that given the current tooling or whether that's something that would need to be handled by a different plugin. We're avoiding the smart commit syntax right now in favor of things that work directly with the interface, but that's apt to change if the tools only go so far.

Regardless, if the takeaway here is that draft pull requests function as expected given the current Jira API restrictions then I think that's fine. It was confusing when I originally saw it, but I see how that could also be a result of our non-ideal workflow.

**Comment by danielfx90** [comment]
@tcbyrd what would happen if the status is set to `UNKNOWN`? Will it prevent the issue from transitioning but at the same time add it to the issue?

Have there been any improvements in JIRA's API to tackle this issue better now?

**Comment by ivan-californias** [comment]
Hi, any update on this issue?

Following up on the conversation, I rather not have the Pull Request be sent to Jira while it is a draft until it becomes ready for review.

**Comment by joseluiscadena** [comment]
agree with last comment, is there any update?

**Comment by samaronybarros** [comment]
Hi, any updates on this issue?

I also agree with @ivan-californias.

**Comment by RiaanVR** [comment]
Any further feedback on this issue @tcbyrd? I stumbled upon this today and have the same workflow as described by the original author, and am fully on board with the solution proposed by @ivan-californias, what is required to move this forward?

**Comment by patrick-tresp** [comment]
Hi there, 
we also would like to have drafts not to be sent to jira since this is misleading our tracking.
A Draft is sometimes kept for multiple days or even weeks and it keeps sticking to a state that implies an active PR.

Looking forward to it!

**Comment by sidhuko** [comment]
This feature should be configurable by the user. I dislike drafts triggering code review. It breaks peers reviewing each others work.

**Comment by tubbo** [comment]
here to chime in and say that i also ran into this issue and it would be amazing if we could get either a different trigger for PRs or possibly a condition where we can check the PR's type

**Comment by matthias-mohemian** [comment]
Any updates here? Would really improve our Jira - Guthub workflow!

**Comment by antoine-roam** [comment]
Another bump here, any update @tcbyrd ?
Any chance this could be reviewed by the Jira team anytime soon?
Cheers.

**Comment by trm42** [comment]
It seems that Atlassian has their own ticket about this one. Probably helps more if people go there to vote the issue:

https://jira.atlassian.com/browse/JRACLOUD-72888

**Comment by rachellerathbone** [comment]
Hi @dpraul. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by smckinney1** [comment]
I would also love to see Draft PRs treated differently for the JIRA integration!

**Comment by brentjensen** [comment]
I would also like to have this feature. We use it to trigger our workflow to move columns and bring work items to people's attention.

**Comment by Reedyuk** [comment]
Same here, currently In-Review column is flooded with draft pr's which are not ready for review.

**Comment by hamirmahal** [comment]
@tebriel and @rachellerathbone, I think this is a feature our team could benefit from, as well. What things do you need from the community to add this?

There's an implementation mentioned by a member of the community, at https://jira.atlassian.com/browse/JRACLOUD-72888, that would be nice for Atlassian to support natively, especially for developers who don't have admin-level access to our organization's `git` repository, the Jira workspace, or either.

**Comment by juniorb2ss** [comment]
Any news about it?

**Comment by bbredewold** [comment]
Bump!

**Comment by suhaasprasad** [comment]
+1

**Comment by tylertrussell** [comment]
+1 from us as well; we'd love for Drafts to not trigger the "Pull Request Created" event

**Comment by GalDayan** [comment]
Any news?

**Comment by nickpassarella** [comment]
+1

**Comment by matthias-mohemian** [comment]
+1

**Comment by verganis** [comment]
+1

**Comment by dpraul** [comment]
To future people popping in here: feel free to comment if you have input! But simply commenting with a "+1" or similar "bump" comments does nothing except create noise for all the subscribers on this thread.

If you'd like to show your support but have nothing to add besides what has already been said, GitHub has a mechanism for your voice to be heard without creating additional noise! Simply leave a 👍 on the top comment and Atlassian will be able to see your input [when they sort by "most reactions"](https://github.com/atlassian/github-for-jira/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). 🙂

**Comment by rafcevallos** [comment]
I agree the draft pr should NOT trigger a jira change.  For example, we have a "Code Review" status for tickets and ideally this would only happen for real PRs and not draft ones.  

I sometimes set up a draft pr when I'm doing file setup for new work and then PMs get excited because it seems the work was done so fast 🤣 .

**Comment by kwdowik** [comment]
+1

**Comment by mjonas87** [comment]
FYI - looks like [some hero](https://github.com/krazziekay) has opened a PR regarding this. Let's give it some love ya'll
https://github.com/atlassian/github-for-jira/pull/1556

**Comment by anastasiyamazheika** [comment]
+1

**Comment by kb-ist** [comment]
Another vote here for draft PRs not triggering transitions in Jira, it causes a lot of confusion.

**Comment by DanielKrofchick** [comment]
@rachellerathbone we're coming up on 4 years since GitHub introduced the draft feature (Feb 14). This thread is about the same age with no progress at all on the issue, or any communication about what Atlassian plans to do. Can you please give us some insight into this problem and what Atlassian's intentions and timeline are for fixing this. Unfortunately I'm not able to comment in the Atlassian [ticket posted](https://jira.atlassian.com/browse/JRACLOUD-72888) earlier here, so this is the only outlet I've found.

**Comment by haydenmatthews** [comment]
Still no update on this? Unable to comment as others have stated on the Atlassian thread.

**Comment by atrigueiro** [comment]
Hi all, we know you’ve been patiently waiting for this feature. We’re pleased to let you know it’s now in final testing stages and should be available soon. We’ll keep you posted on this issue and you can also follow the updates on [this PR](https://github.com/atlassian/github-for-jira/pull/1556), stay tuned.

**Comment by atrigueiro** [comment]
I’m happy to announce this feature is now available for everyone! New draft PRs will now be highlighted as DRAFT in your Jira issues. Thanks so much for your patience and let us know what you think of the change.

<img width="428" alt="Screenshot 2023-10-03 at 2 06 40 pm" src="https://github.com/atlassian/github-for-jira/assets/58801956/63bfdad0-5660-409c-a81e-dfd7d279fc8e">

**Comment by usmonster** [comment]
Thank you for the announcement @atrigueiro! I'm however not sure the new feature fulfills this issue's core request (i.e. opening draft PR shouldn't trigger "Pull request created" action). If this is the case, can you please reopen it? Thanks!

**Comment by hyei** [comment]
We can now check pullRequest.state for "draft" to avoid transitioning for those who are not following JIRACLOUD-78888, but the transiton from draft to ready for review PR should probably trigger "Pull request created", if there is other way to detect this transition.

**Comment by hipages-songyixing** [comment]
just had a check,  the transition from `draft` to `ready` won't trigger `Pull request created` again.

**Comment by GoncaloBastos** [comment]
This issue is not resolved!

**Comment by tilmanul** [comment]
It would be great to get it a) solved in general and b) also for Data Center solved.

**Comment by lkraav** [comment]
Mid-2024: I'm just joining this dance half-baked "PR created" workflow dance. It's possible we have to create a new issue, because re-opening closed issues (even if it's arguably incorrectly closed) has its own various workflow gremlins associated.

Maybe @atrigueiro or @rachellerathbone can lead the way to the new GH issue on how to get Draft -> Ready transition working correctly?

Just re-triggering "Pull request created" could be a sane option looking at it from surface level, but side-effects?

Without PR workflows right to a tee, tool-hopping is back on the table for many, I'm sure.

**Comment by theklr** [comment]
+1 on resolution needed

**Comment by thornjad** [comment]
Checking in again in the new year, is there any solution to this yet?
