### ISSUE TITLE
PR not syncing with JIRA

### ISSUE THREAD

**Issue by nizzantalon** [atlassian/github-for-jira#1825]
Since Thursday Jan5 ~8am UTC our Github PRs have stopped syncing with JIRA.
I think it may be related to this PR https://github.com/atlassian/github-for-jira/pull/1821 which changed the regex identifying the tickets since it now only looks for tickets wrapped by brackets.

**Comment by mboudreau** [comment]
@nizzantalon I need to know what's your jira domain or Github organization name so I can look up the logs associated with your issue.  Thanks

**Comment by mboudreau** [comment]
Disregard, I see you opened a support ticket with Atlassian.

**Comment by rachellerathbone** [comment]
As there's a support ticket for this, I'm going to go ahead and close this issue. Feel free to reopen if you require further assistance @nizzantalon.
