### ISSUE TITLE
Migration Support

### ISSUE THREAD

**Issue by tayportinga** [atlassian/github-for-jira#1832]
Hello...

We are looking to migrate Bamboo to GitHub Actions and Bitbucket to GitHub. We also use Pantheon with some complexity.

Question is: Do we create a formal account with GitHub and open a Migration ticket to discuss, get some direction and support?

Kind Regards 
Andy Pawl

**Comment by tayportinga** [comment]
Any update on this?

**Comment by rachellerathbone** [comment]
Hey @tayportinga. I would recommend opening a [support ticket ](https://support.atlassian.com/jira-software-cloud/). They should be able to assist you with your query.

**Comment by rachellerathbone** [comment]
Hey @tayportinga. Hopefully you were able to create a support ticket. I'm going to go ahead and close this but please feel free to reopen if you have further questions.
