### ISSUE TITLE
Handful of users cannot create branches

### ISSUE THREAD

**Issue by jbparker** [atlassian/github-for-jira#1833]
We have a handful of users that cannot create branches using GitHub for Jira.

When selecting the repository, the call to get branches fails and error message box with the text **We couldn't fetch the branches because something went wrong. Please try again.** appears:

![Create branch issue 2](https://user-images.githubusercontent.com/5770169/211640033-19727d30-1116-40ec-8099-1392472d31b1.png)

When navigating directly to the URL that provides the JSON payload of branches (`https://github.atlassian.com/github/create-branch/owners/{owner}/repos/{repo}/branches?jiraHost={jira_host}`) a 500 HTTP response code is
 is returned with the sole response body text of **Internal Server Error**.

The user in question exists in GitHub and has logged out & back into both GH & Jira.

Anywhere for us to check what might be causing an issue here? I'm assuming there is something that can't be mapped for the user that is causing the user token retrieval to fail.

**Comment by joshkay10** [comment]
Hi @jbparker - If its only some users and not all I would expect that it could be permissions based, we have had a similar issue with permissions in the past. If you could double check that the users in question have the correct access to the repo on GitHub that would be the best start. If permissions look ok I can see if there is anything going on from our end as well.

**Comment by jbparker** [comment]
Hi @joshkay10 - Thanks for the response! I verified that one user isn't added in GitHub (makes sense!) and the other has **Write** access to the repository selected above.

Is it possible that somehow the user in GitHub is not properly found based on the user in Jira? I'm unsure if that conjecture holds up to how the integration makes that link between the two systems.

Other than that shot in the dark, I'd love to see if there is anything else happening on your end that might shed some light.

**Comment by joshkay10** [comment]
We authenticate directly with GitHub so the Jira user wont effect those permissions only the GitHub user.

I'll have a look through and see if we get any extra detail about the 500.

Did you update the first users access and have success?

**Comment by jbparker** [comment]
@joshkay10 yes, we were able to get them working as expected. It's just the one user that has **Write** access to the repository that is the real concern.

**Comment by daryl-nathanson** [comment]
@rachellerathbone - I see this is labelled as awaiting response still, but did you or @joshkay10 see Jordan's response yet?

**Comment by bgvozdev** [comment]
Let's continue here: https://github.com/atlassian/github-for-jira/issues/1845 . We've fixed a bunch of issues with this feature recently, please report to the aforementioned one in case you still experience troubles!
