### ISSUE TITLE
Link Jira issues in Jira "Code" view.

### ISSUE THREAD

**Issue by birdsarah** [atlassian/github-for-jira#1836]
On the Code view, screenshot below

![image](https://user-images.githubusercontent.com/1796208/212247847-ce50da4d-299d-43e9-8d7e-84c964b6226f.png)

It would be great if there was a column that linked off to the Jira issue.

**Comment by rachellerathbone** [comment]
Hi @birdsarah. Unfortunately, this component is owned by another team at Atlassian. Please open a [support ticket](https://support.atlassian.com/jira-software-cloud/) and our support staff will connect you with the correct team.
