### ISSUE TITLE
Cannot Connect my GitHub organization to my Jira site

### ISSUE THREAD

**Issue by iasik-x** [atlassian/github-for-jira#1838]
When I click on Connect, nothing happens.

![Screenshot 2023-01-16 134808](https://user-images.githubusercontent.com/122726051/212660214-6a32017d-8650-4dd9-a004-0ac7195a7413.png)

**Comment by rachellerathbone** [comment]
Hey @iasik-x. This usually happens when you try to connect to an org that you don't have permissions for. I've created an issue in our backlog to make sure we surface error messages. In the meantime, can you please confirm you have admin access to the org you're trying to connect to?

**Comment by iasik-x** [comment]
Hi @rachellerathbone. Yes, I have admin access to the org.

**Comment by rachellerathbone** [comment]
Hmmm interesting. Can you **Connect another Jira cloud site**, install the app on another org and then try connecting to that? It would be good to narrow it down: is the issue related to this one org or is there something going on when trying to communicate with your GH account?

**Comment by rachellerathbone** [comment]
Also, can confirm you are logged into your GH account and are logged into the correct GH account? When I log into my secondary account and try to connect I run into the same issue. Can you do me a favour, when you try to connect again, if nothing fails can you open up the developer console? Hit "Cmd + Option + I" (mac) or "Ctrl +Shift +J" (windows). From there, click the console tab (if not already selected) and click the Connect button again. You should see an error come up in your console. Click the link. This will take you to the network tab. Next, click on the item under 'Name' and then select the response tab. Can you please send through the error you see there?

**Comment by kat-iasik** [comment]
I stop trying to connect to the org. Then I start to use issue keys in the commits, it automatically connected to the repo. So my problem is somehow solved.

**Comment by uskpea** [comment]
<img width="447" alt="githunjiraissue" src="https://user-images.githubusercontent.com/88337031/216357173-fb4436df-6f9a-4e90-b3ec-ebb0d119bb33.PNG">
I am an Org admin for the GitHub organization and tried to create a branch and was unable to pull the list of repositories from the organization.  It only provided some latest lists but cannot search a repository in the Search.  It is not functioning correctly.  Any resolution to this issue?

**Comment by bgvozdev** [comment]
Hey @uskpea , we have a dedicated issue for create-branch functionality, please have a look especially at https://github.com/atlassian/github-for-jira/issues/1845#issuecomment-1413136840 . If you didn't find your answer there, please continue there.

Looks like the original problem has been solved here. Closing the issue.
