### ISSUE TITLE
Can't connect to non-organization repo

### ISSUE THREAD

**Issue by recatek** [atlassian/github-for-jira#1884]
The dialog to connect to a repo from within Jira only presents organization repos, it does not allow me to search for or select any repos on my account outside of any organization.

**Comment by bgvozdev** [comment]
GitHub for Jira is a GitHub app, and GitHub app are designed to be installed on org level. Please find more details here: https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps#about-github-apps . I doubt there's anything we could do.
