### ISSUE TITLE
How to get Information about commits in Jira

### ISSUE THREAD

**Issue by claudiaalvarez-df** [atlassian/github-for-jira#1900]
Hello !

We just installed the GitHub for Jira application to interact with GitHub platform and be able to connect the developers' work with Jira issues. We'd like to know more about that application in order to identify where the data is being stored. For example the commits, info remains in Github or now lives in an special table in JIRA.

The Jira Team tell us this.... 
" .. The data is stored in DataDepot, which is a set of microservices and is managed by  GitHub for Jira app (that is the mediator between GitHub and DataDepot) uses [this API](https://developer.atlassian.com/cloud/jira/software/rest/api-group-development-information/#api-group-development-information) and AFAIK data depot stores everything that it receives .... " 

The point of this ticket is to know how can we consume this information and bring light on this matter.
Any Help is greatly appreciated

**Comment by bgvozdev** [comment]
Hi @claudiaalvarez-df 

The data that is consumed by the aforementioned API is visible in Jira in several places:
 - issues: https://support.atlassian.com/jira-software-cloud/docs/view-development-information-for-an-issue/
 -  deployments page https://support.atlassian.com/jira-cloud-administration/docs/what-is-the-deployments-feature/
 - project's code page https://support.atlassian.com/jira-software-cloud/docs/enable-code/
 - etc

You can see more details how this data could be used here: https://support.atlassian.com/jira-cloud-administration/docs/integrate-with-development-tools/

Is there any specific use-case you are pursuing?

**Comment by atrigueiro** [comment]
Closing as there has been no response for over 6 months.
