### ISSUE TITLE
exclude certain commits from appearing in Jira even if the commit contains the Jira issue key

### ISSUE THREAD

**Issue by aylin-solak** [atlassian/github-for-jira#194]
Dear all,

I want to exclude certain commits from appearing in my Jira issue even if the commit contains the Jira issue key.

For example, when a commit has the word "staging", i do not want it to be seen in commit list.

thank you very much for consideration in advance.

Best Regards,
Aylin

**Comment by rachellerathbone** [comment]
I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this. I'm not sure we'll be able to do anything as it would be hard for us to determine what users do and do not want to exclude but we can at least have a discussion about it.

**Comment by rachellerathbone** [comment]
Hey @aylin-solak. The team triaged this issue and determined that manual de-association is unlikely to have real customer impact or benefit so I'm going to go ahead and close this issue. That said, if this is something that you would find highly valuable, please feel free to reopen this and reach out again.

**Comment by nickfletcherr** [comment]
@rachellerathbone This issue is now a lot more problematic with Jira's automation rules. We have an automation rule to close tickets when the PR is merged, but this is causing tickets that are mentioned to be closed even if they are not actually being addressed by the PR.
