### ISSUE TITLE
Assignee is not mapped to email using triggers

### ISSUE THREAD

**Issue by jayKayEss** [atlassian/github-for-jira#198]
We'd like to transition tickets to "In Progress" when an engineer creates a new branch.

JIRA does not map my Github email address to my JIRA user when using the "Branch Created" trigger. The trigger fires and the ticket is transitioned, but the user is "Anonymous" and JIRA does not reassign the ticket.

The assignee *is* mapped as expected using Smart Commits, but we'd prefer to use triggers for this use case.

My Github account has two emails, a personal one and a work one. The work address is assigned to our work Organization, and I have tried making the work address my "primary"; neither of these fixes the issue.

JIRA notifications come through as "Anonymous":

![image](https://user-images.githubusercontent.com/102251/59043997-43a01480-884b-11e9-9a0e-bf323ca68716.png)

Trigger config:

![image](https://user-images.githubusercontent.com/102251/59044289-e48ecf80-884b-11e9-940c-e154edddca15.png)

![image](https://user-images.githubusercontent.com/102251/59044360-04be8e80-884c-11e9-8350-69caaf0c0585.png)

**Comment by gjabouley-invn** [comment]
Same comment here, maybe at least replace Anonymous by Github, if it could be possible...

**Comment by MythosRaconteur** [comment]
Would love to see this as well... We know who created the branch, it would be nice to have that person assigned to the ticket.

**Comment by rachellerathbone** [comment]
Hi @jayKayEss. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by ccrolf** [comment]
Hi Jay,

is this also an issue in Automation for Jira (A4J)? A4J is aimed at replacing transition triggers, as it's a much more extensible platform.

Cheers,
Christian

**Comment by rachellerathbone** [comment]
Hey @jayKayEss. I hope the suggesstion made by @ccrolf was able to help you out with this issue. Given that we haven't had a response in over a month, I'm going to go ahead and close this issue. Please feel free to reopen/reach out again if you need help with anything.

**Comment by bendang-okta** [comment]
hi @rachellerathbone I have this same issue currently where upon PR creation, my jira tickets will go from Open to Triaged as anonymous.

I looked at the A4J but it looks like its an extra package.  Is there a way to make this current Jira and Github integration work to make sure its showing as the user that created the PR instead of Anonymous?  I would even be happy if instead of Anonymous it showed up it as Github.
