### ISSUE TITLE
Idea: Write Smart Commits parser

### ISSUE THREAD

**Issue by jnraine** [atlassian/github-for-jira#210]
We've received a number of bug reports around how [Smart Commits](https://confluence.atlassian.com/fisheye/using-smart-commits-960155400.html) data is extracted from text. For example, https://github.com/integrations/jira/issues/189.

Right now, we extract issue keys and other information a few big [regex patterns](https://github.com/integrations/jira/blob/0cb6270d7c7dea71c0a188013ddcbbadaa370452/lib/transforms/smart-commit.js#L7) and a couple functions. The code is concise and serves most cases but misses on others.

As a potential future change, we may be able to more reliably parse text as Smart Commits if we used a parser, written by hand or with a library like [Nearley](https://nearley.js.org/).

This is only an early stage idea. Suggestions and questions welcomed!

### Goals

- Full support for [Smart Commits](https://confluence.atlassian.com/fisheye/using-smart-commits-960155400.html)
- Extensive test coverage, including every example from JIRA and our customers to ensure no regressions occur.

### Smart Commits examples

Below is an incomplete list of test cases that need support. See more examples in the [Smart Commits docs](https://confluence.atlassian.com/fisheye/using-smart-commits-960155400.html).

| Description                           | String                                                                                    | Result                                                      |
|:--------------------------------------|:------------------------------------------------------------------------------------------|:------------------------------------------------------------|
| Hash-prefixed issues.                 | `#JRA-123`                                                                                | Associate to JRA-123                                        |
| Case insensitive issues.              | `jra-123`                                                                                 | Associate to JRA-123                                        |
| Embedded issues.                      | `features/jra-123`                                                                        | Associate to JRA-123                                        |
| Single command on multiple issues.    | `JRA-123 JRA-234 JRA-345 #resolve`                                                        | Resolve JRA-123, JRA-234, JRA-345                           |
| Multiple commands on multiple issues. | `JRA-123 JRA-234 JRA-345 #resolve #time 2d 5h #comment Task completed ahead of schedule`. | Resolve, log time, and comment on JRA-123, JRA-234, JRA-345 |

**Comment by scepticulous** [comment]
I think that's a nice idea 💟 

TBH I think doesn't seem more complex than maintaining nested regular expressions. 

Would you mind adding a few more details to this issue? Like:
* A link to the Atlassian smart-commit docs
* the general smart-commit format as text
* The Goal of a good unit test coverage to avoid future regressions and to make it easy for documentation.
  * Subgoal: Supporting all currently tested formats, the format requested in #189 + the examples from their website as unit tests

**Comment by rachellerathbone** [comment]
Hi @jnraine (again). Also flagged this one with 'to triage' so my team can discuss.
