### ISSUE TITLE
Interactive Smart Commits site

### ISSUE THREAD

**Issue by jnraine** [atlassian/github-for-jira#212]
Build an interactive site—like [rubular.com](https://rubular.com/)—to help developers learn how Smart Commits works in practice. If we go ahead with a Smart Commits parser (#210), it would take minimal effort to setup a static site, hosted on GitHub Pages.

![image](https://user-images.githubusercontent.com/300976/62247032-d23b9880-b399-11e9-9850-6e9fba03f15d.png)

This should help us debug or alleviate issues like https://github.com/integrations/jira/issues/206: if a string parses correctly, we know the issue is elsewhere. If it doesn't, it's easy to see why and fix it.

Filing this as a future idea to circle back on later.

**Comment by rachellerathbone** [comment]
Also flagged for discussion.

**Comment by rachellerathbone** [comment]
Closing this issue as it is unrelated to the integration. Have added it to a lists of possible project ideas that someone from our org may end up picking up.
