### ISSUE TITLE
Sync configuration

### ISSUE THREAD

**Issue by jnraine** [atlassian/github-for-jira#215]
The existing sync isn't configurable. While it works for the majority, it doesn't meet the needs of every user. This manifests in two ways: we _sync too much_ or we _don't sync enough_.

When a user installs the integration, it automatically syncs every repository (all commits on master, 50 commits on other branches). For organizations with many repos or repos with many commits, this can take hours. Until the sync completes, the user is not able to see incoming updates.

On the other end, when a non-master branches contain historical data, the default sync of 50 commits for non-master branches won't sync historical data.

## Use cases

- **Large repo with no historical data.** For example, when an org contains a fork of the Linux repository, which doesn’t contain any JIRA references. Synchronizing this repository takes hours, delaying the customer's ability to use the new integration.
- **Large repository with little historical data.** For example, when an org contains a repository with years of history but only cares to sync the last few months of data. (This can happen when the user only recently started using JIRA.)
- **Historical data on non-master branches.** For example, an org has long-lived branches, like `development` or `staging`, which contain historical data. However, because we only sync the last 50 commits on non-master branches, these references aren't pulled into JIRA.
- **No historical data.** For example, an org just signed up for JIRA so there is no historical data to synchronize.
- **Many irrelevant repositories.** For example, when an org has hundreds of repos but only one or two contain JIRA references.

## Considerations

- Many users are well-served by the existing sync. We should consider maintaining this experience while progressively disclosing more advanced options for those who require it.
- The deprecated DVCS Connector provides a number of configuration options that can act as a foundation. 📹 [Watch demo](https://drive.google.com/open?id=1F8q-jwvvWqcaxluTkVIZ35eJBm4mGn4E).

## Potential solutions

There are a number of elements that could be added to the UI. We may end up combining several of these solutions.

1. **Repo list.** After installation, present user with a list of repositories. By default, check every repository. Allow the user to select/deselect repositories. Provide a "Select all/deselect all" to make it easy to sync many or only a few.
2. **Sync time period.** After installation, on the popup described in solution 1, allow the user to choose how far back to sync (e.g., 2 months, 1 year, all).
3. **Branch sync.** Allow the user to trigger a complete historical sync for a non-master branch.
4. **Branch whitelist/pattern.** In addition to a complete historical sync for master, allow the user to specify other branches to sync. This may be a comma-separated list or a pattern (e.g., `(master|development|feature-.+)`).

**Comment by rachellerathbone** [comment]
Another issue to triage for you. Stay tuned.

**Comment by rachellerathbone** [comment]
Added a ticket for this to our backlog. Might be a while before we get around to it (post migration) but it's in our sights. Stay tuned!
