### ISSUE TITLE
Sync status stuck in "ACTIVE" for days

### ISSUE THREAD

**Issue by reillydavis** [atlassian/github-for-jira#221]
It seems this is a widespread issue, but in migrating from the DVCS connector to this app, the sync never completes. 

Atlassian nor GitHub seem to be able to provide any support. What's going on? Is anyone else having this problem?

![image](https://user-images.githubusercontent.com/4644614/62419655-6461cc00-b63a-11e9-9d92-8bcca4f84808.png)

**Comment by rachellerathbone** [comment]
Hi @reillydavis. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

When the migration of this app is complete, my team will be looking into potential ways to improve the sync process to address a number of issues raised by our users/contributors. Stay tuned 😄

**Comment by rachellerathbone** [comment]
Hey @reillydavis. The team at Atlassian has made a number of changes to syncing. Could you please let me know if this is still an issue for you?
