### ISSUE TITLE
Bug regarding Time of ticket updation

### ISSUE THREAD

**Issue by SikindarMirza** [atlassian/github-for-jira#290]
Assume a person A is in UK and the other person in India.
If UK person did some modification to the ticket at 11:30 UK time, the person in India see the history and find changes done at 11:30 which is wrong. he must see as per India time(IST)

**Comment by rachellerathbone** [comment]
Hi @SikindarMirza. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by rachellerathbone** [comment]
Hi @SikindarMirza. I've created a ticket in my team's backlog for us to investigate. We'll update you on the progress. Stay tuned.

**Comment by mboudreau** [comment]
sorry, this was closed by mistake.

**Comment by mboudreau** [comment]
Actually, I believe this was fixed as part of the ownership transfer to Atlassian.
