### ISSUE TITLE
Show deployments in Jira

### ISSUE THREAD

**Issue by pznamensky** [atlassian/github-for-jira#310]
Hi there,
We are using GitHub deployment api for our apps, and we've lots of stage environments.
It will be super-useful if deployments appear in Jira alongside with PR's, commits and branches. Is it possible?

**Comment by taylor-resi** [comment]
+1

**Comment by msteward** [comment]
Is this related to the newer Deployment views in Jira? (https://support.atlassian.com/jira-software-cloud/docs/integrate-your-deployment-pipelines-with-jira/). There are integrations with some CI providers but not with GitHub Actions yet (other than using the API yourself).

**Comment by rachellerathbone** [comment]
Hi @pznamensky. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

This is something we're actively working on at the moment. Stay tuned 😄

**Comment by pznamensky** [comment]
Glad to hear it!
Thank you!  :slightly_smiling_face:

**Comment by lucduong** [comment]
@rachellerathbone Is that possible to update deployment info from Github actions? I tried to find the related documents but couldn't found the way to do it. Could you support me on this case?

**Comment by atrigueiro** [comment]
Hi @pznamensky, GitHub Actions is now fully integrated with Jira, which means you can see your Builds and Deployments from GitHub in your Jira issues. You should've received an email from GitHub asking for a permissions review and once that's accepted, your CI/CD data will start flowing automatically into Jira when a Jira issue key is used on a commit message or branch name.

Please let us know if you have any issues.

Thank you,
Amanda.
