### ISSUE TITLE
Does not appear to update sub-tasks

### ISSUE THREAD

**Issue by chrisgagne** [atlassian/github-for-jira#316]
Our dev team uses Jira "sub-tasks" to track the progress against larger backlog items (Jira "issues"). It'd be great if I could issue a Smart Commit against a sub-task rather than just an issue.

**Comment by rachellerathbone** [comment]
Hi @chrisgagne. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by chrisgagne** [comment]
That's wonderful, thanks @rachellerathbone! I invite your team to think of this through the usual Scrum framework: the backlog item (issue in Jira) reflects the what while the task (sub-task in Jira) reflects the how. A developer is more likely to log work against a sub-task than a issue as that is where the "how" of the work is most likely to be described.

**Comment by thombergs** [comment]
Hey @chrisgagne,

this integration should work with any type of Jira issue, including sub-tasks. You would just have to put the issue ID of the sub task in your commit message and the commit should show up in the sub task in Jira.

And smart commits should work with sub tasks, as well. 

Or do you mean something else? What exactly would you like to achieve?

**Comment by rachellerathbone** [comment]
Hey @chrisgagne. Given it's been a few months since we've had any activity on this issue I'm going to go ahead and close it. If the above response didn't help and you need further assistance, please feel free to reopen.
