### ISSUE TITLE
"Get Started" From Manage Apps in JIRA leads to "App is not responding" page. 

### ISSUE THREAD

**Issue by AparnaJN** [atlassian/github-for-jira#330]
Hello, we used to have Github integration working without any trouble on our JIRA account without any trouble. Recently the integration seems to have been broken. I tried installing it again from the Marketplace. While trying to configure the app, I end up here (screenshot below). I have tried a couple of times to uninstall Github app and reinstall. But doesn't seem to work. Appreciate any help that can be provided. Thanks!

![image](https://user-images.githubusercontent.com/14106206/78096351-ec87b380-740b-11ea-8286-9eec7b2e51f2.png)

**Comment by rachellerathbone** [comment]
Hi @AparnaJN. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

This is an issue that my team is currently looking into and have linked your issue in a ticket in our backlog. Stay tuned 😄

**Comment by rachellerathbone** [comment]
Hey @AparnaJN. Given that it's been a while since we've seen any activity on this issue, I'm going to go ahead and close it. If you need further assistance, please feel free to reopen and reach out.
