### ISSUE TITLE
Identifying JIRA tickets in conventional-commits

### ISSUE THREAD

**Issue by gazal-k** [atlassian/github-for-jira#354]
We use https://www.conventionalcommits.org/en/v1.0.0/ in our team.

So our commits look like:
```sh
type(scope): commit comment

long description

re #JIRA-ID
```

We see that if we do `re #[JIRA-ID]` in the commit, then it links to JIRA when we create a PR. But we'd prefer not to use the `[]`

**Comment by Berkmann18** [comment]
Using the ESLint commit convention and having either of the following commit messages get Jira to pick up both (so I'll guess that it's the same for the Angular, JSHint, Atom, ... commit conventions):
```
New: PRO-37: Added something

Bla bla
```
```
Update: Some stuff
Fix PRO-39
```

I found this when I was testing if Jira was picking up `PRO-xx` (`PRO` being a random substitute for a real project code) or if I needed to have `[PRO-xx]` or `#PRO-xx` in the commit message and it worked.

**Comment by rachellerathbone** [comment]
Hi @gazal-k. As long as a commit message contains the issue key, it will show up in the corresponding issue in Jira. Square brackets are not needed.

Please let me know if I have understood your issue correctly so I can close this out/follow up.

**Comment by iwt-twirth** [comment]
I think there is just the one problem that according to the `conventional-commits` v1.0.0 specification a reference in the footer has to correspond with the form:
`<word-token> #<reference>` or `<word-token>: <reference>`

Where *word-token* is a single word or multiple words separated by `-`.

According to the spec I think a valid footer should look as follows: `Jira-Ticket: PRO-123`
Will this still be recognized by Jira?

**Comment by gazal-k** [comment]
> Hi @gazal-k. As long as a commit message contains the issue key, it will show up in the corresponding issue in Jira. Square brackets are not needed.
> 
> Please let me know if I have understood your issue correctly so I can close this out/follow up.

Sorry, I guess I hadn't followed up on this in a while.

Yes, the linking from Jira works. But the link back from GitHub to Jira seems to only work when the Jira id is in `[]`. Like `re [JIRA-123]` as opposed to `re #JIRA-123`.

**Comment by rachellerathbone** [comment]
Hey @gazal-k. Good news. This has been added to our roadmap. While I can't provide a timeline of when this work will be completed, rest assured that it is in our sights. I'll update here again when I can.

**Comment by gazal-k** [comment]
Good to know. But we have since tweaked our convention for JIRA references in the footer to use the syntax: `re [JIRA-123]` which works like a charm 🙂, and does not seem to be really going against the spec for https://www.conventionalcommits.org/en/v1.0.0/.

**Comment by ccrolf** [comment]
Thanks for the work-around! As it's working now, we will close this issue :)

**Comment by iwt-twirth** [comment]
@gazal-k Just in my understanding, `re [JIRA-123]` does go against the spec, as:

> One or more footers MAY be provided one blank line after the body. Each footer MUST consist of a word token, followed by either a `:<space>` or `<space>#` separator, followed by a string value.

but your workaround does neither contain `:<space>` nor `<space>#`.
