### ISSUE TITLE
Issues not linking in GitHub PR's

### ISSUE THREAD

**Issue by jamesmcguirepro** [atlassian/github-for-jira#398]
If I link more than a handful of Jira tickets in a GH PRs, the bot will only update the first few.

Ie:
If I entered these in a PR description:
```
[JIRA-1]
[JIRA-2]
[JIRA-3]
[JIRA-4]
[JIRA-5]
[JIRA-6]
[JIRA-7]
```
Not all of them would be converted to links.

**Comment by hilnius** [comment]
@jamesmcguirepro do you get any issue linked ? I have the same issue as you except I get 0 conversion to link

**Comment by jamesmcguirepro** [comment]
The first few will link @hilnius

**Comment by rachellerathbone** [comment]
Hi @jamesmcguirepro. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

Can you please let me know if this is still an issue so my team can follow up?

**Comment by jamesmcguirepro** [comment]
@rachellerathbone Yes

**Comment by rachellerathbone** [comment]
Ok. I've created a ticket in our backlog so we can look into this. We'll keep you posted.

**Comment by atrigueiro** [comment]
Hi @jamesmcguirepro hope you're doing well. We've fixed this issue and should be working as expected from now on. Please let us know if you run into it again. Thanks!
