### ISSUE TITLE
Please add a configurable separator for the issue key, or at least space in addition to -

### ISSUE THREAD

**Issue by MaxTranced** [atlassian/github-for-jira#426]
Per https://github.com/integrations/jira/issues/188 only `#ABC-123` and `ABC-123` are supported. After https://github.com/integrations/jira/issues/220 lower case / mixed case will also be supported, most likely. It would be really helpful for the more forgetful people to also support a short list (or customizable list?) of separators, which ideally would include the space character. So `ABC 123` would also work. If this would lead to confusion it could also be restricted to this type of usage: `[ABC 123]`.

Thank you for considering this feature!

**Comment by rachellerathbone** [comment]
Hi @MaxTranced. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

This is something we're looking into improving and have several tickets in our backlog. Stay tuned 😄

**Comment by rachellerathbone** [comment]
Hi @MaxTranced. Thanks for your patience while waiting for me to get back to you again on this issue. Unfortunately, the team has discussed this issue and determined that this request is not feasible as it would require a major redesign of the app. 

Going to close this issue but please reach out to let us know if there is anything else we can assist with.
