### ISSUE TITLE
Branch squash with work time allocations not reflected in Jira

### ISSUE THREAD

**Issue by rawong215** [atlassian/github-for-jira#458]
When a branch with files committed that have recorded work time using smart commits (#time 3h) is squashed, Jira does not reflect the correct time nor branch removal in its view.  Is this a known issue and if there are any workarounds other than manually removing time in Jira.

**Comment by rachellerathbone** [comment]
Hi @rawong215. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by rachellerathbone** [comment]
Hey @rawong215. I've created a ticket in my team's backlog and we'll update you when we can. Stay tuned 😄

**Comment by thombergs** [comment]
@rawong215 Can you please check what the commit message of the squashed commit looks like? Does it contain the `#time 3h` string properly? Or is this keyword maybe garbled somehow by the squashing?

**Comment by rawong215** [comment]
The issue is not with the commit message having the proper format of the time log entry.  It is properly entered in the comment as #time 3h.  The time does register properly after the commit in the branch within the Jira issue.  The issue here is if there is development work under a branch with time log entries appearing in the Jira issue as commits.  If suddenly the work the branch is deemed not necessary and the branch itself is deleted in GitHub, the Jira issue does not reflect the removal of the branch, commits and time logged under the commits.  If we are tracking the work time for the Jira issue it is now showing inaccurate work time as a branch with commits were removed.

**Comment by rawong215** [comment]
Hello, has there been any updates? Thx.

**Comment by ccrolf** [comment]
Hi @rawong215 , 

from my understanding this is expected behavior. Because the branch being removed doesn't mean the time wasn't spent on the task.

It might be that the time tracking functionality doesn't support your use-case. Do you use it to track something other than the total time developers spend on it?

**Comment by rachellerathbone** [comment]
Hey @@rawong215. As we haven't heard from you in a while, I'm going to go ahead and close this issue. Please reopen if you have any other questions.
