### ISSUE TITLE
{{pullRequest.destinationBranch}} smart value is not working as expected in Automation for Jira

### ISSUE THREAD

**Issue by ezhapa** [atlassian/github-for-jira#469]
Seems like there is a bug with how GitHub responds to 'Automation for Jira' for the {{pullRequest.destinationBranch}} smart value.
Basically, the {{pullRequest.destinationBranch}} smart value is expected to return the name of the destination branch but is actually returning the URL. 
Whilst the {{pullRequest.destinationBranch.url} smart value which should be printing the URL, is actually returning an empty value. The smart value {{pullRequest.sourceBranch}} works as expected.

The behavior for the same smart value for GitLab and BB works fine. Here's the documentation for how these smart values work:https://support.atlassian.com/jira-software-cloud/docs/smart-values-development/

**Comment by rachellerathbone** [comment]
Hey @ezhapa. So we can assist you, could you please provide an example of a use case where you are using this smart value?

**Comment by rachellerathbone** [comment]
Hey @ezhapa. Given that it has been over a month since we last heard from you, I'm going to go ahead and close this issue. Please feel free to reopen/reach out again if you need help with anything.

**Comment by mboudreau** [comment]
Yep, @HawkAPFM is right.  We are sending the wrong value: https://github.com/atlassian/github-for-jira/blob/main/src/transforms/pull-request.ts#L114

Reopening.  We should fix this ASAP.

**Comment by mboudreau** [comment]
@ezhapa @HawkAPFM Good news, this has been fixed and deployed.  To fix your current smart values, please do a complete resync of every organizations from your Github for Jira configuration page.  Please let me know if you're getting any issues.  Cheers.
