### ISSUE TITLE
Trigger an action when a new release is created on GitHub

### ISSUE THREAD

**Issue by felixveysseyre** [atlassian/github-for-jira#487]
Hi !

It would be nice being able to trigger an action when a new release is created on GitHub.

Does this feature is already part of your roadmap ?

Thanks !

**Comment by thombergs** [comment]
@felixveysseyre interesting idea. Can you elaborate a bit on what exactly you would want to trigger when a new release is created? What is your concrete use case? That would be interesting to know so we can evaluate if this is something we'll want to follow up on.

**Comment by felixveysseyre** [comment]
@thombergs thank you for your answer !

My Jira issue status workflow looks like this, `Todo` > `InProgress` > `InReview` > `Done` > `Released`

The transition from `InReview` To `Done` is handled by Jira automation when the associated pull-request is merged.
When a release is created on GitHub, I would like to transition all Jira tickets with `Done` status, to the`Released` status.

Does it make any sense ?

**Comment by msteward** [comment]
> @thombergs thank you for your answer !
> 
> For this example, let says my Jira issue status workflow looks like this: `Todo` > `InProgress` > `InReview` > `Done` > `Released`
> 
> The transition from `InReview` To `Done` is handled by Jira automation when the associated pull-request is merged.
> When a release is created on GitHub, I would like to transition all Jira tickets with `Done` status, to the `Released` status.
> 
> Does it make any sense ?

It looks like with the updated GitHub Integration released recently with Jira that you are now able to get deployment information from GitHub. This lets you add a Jira Automation to trigger a issue transition (e.g. from Done > Released in your example) upon successful deployment to production if that makes sense?

<img width="759" alt="Screen Shot 2021-07-27 at 5 07 18 PM" src="https://user-images.githubusercontent.com/685691/127243033-475dc089-e7c2-4823-a7a8-ab98a6380aae.png">

**Comment by atrigueiro** [comment]
Hi @felixveysseyre, what @msteward mentioned above is correct. I'm going to go ahead and close this issue but if you notice anything not working as expected regarding getting deployment information in Jira, please feel free to reopen this and reach out again.
