### ISSUE TITLE
Remove "write access" to code.

### ISSUE THREAD

**Issue by andymckay** [atlassian/github-for-jira#54]
Currently the Jira app on GitHub requires "Write access". In a meeting, neither myself, @tcbyrd or @bkeepers could figure out why. Let's remove that permission from the Jira app.

**Comment by akropp-stripe** [comment]
The documentation still says it requires write access. Is this correct?

**Comment by tcbyrd** [comment]
@akropp-stripe Can you point out the documentation where you see this? On GitHub It does [require](https://github.com/integrations/jira#github-permission-scopes) write access to Issues and Pull Requests, but not write access to code (which is what we updated in this Issue). On Jira it requires write access to [Development Information](https://github.com/integrations/jira#jira-permission-scopes) only.

**Comment by akropp-stripe** [comment]
I see, I think I misunderstood the write access part. Thanks
