### ISSUE TITLE
Allow configuration for showed builds in developement tab in Jira

### ISSUE THREAD

**Issue by jcdan3** [atlassian/github-for-jira#586]
Hi,
How can I configure which build(s) to be shown on the development -> Builds tab. See screenshot below, I would like for instance to only show the _Pull-Request Run Dev_ result and not display the others (from the Github Actions section).

if this is not possible, do you plan on adding such feature?

![image](https://user-images.githubusercontent.com/40872726/128220513-78bfe02f-a63c-43c1-bbf2-b920c4b0f7b2.png)

**Comment by mboudreau** [comment]
Hm, I think we're going to need more information about your Github branching/PR/build structure first before we can try to assess the problem with how many builds you have in Jira.

**Comment by jcdan3** [comment]
The thing is that every workflow that is ran (being a build or not) is stated as a built in this window.
E.g. _Is PR Approved by QA_ is has its own file (is_approved_by_qa.yml), but does not produce a build.

So every workflow appears in the windows, but I would like to select which one to show.

If you need more information, please be specific.
Thanks!

**Comment by mboudreau** [comment]
Ah right, that makes sense.  We'll have to figure out a way of doing this at scale as it wouldn't be efficient to have filters at the top level as it would change per repository I'd imagine.  I wonder if there's a way to add metadata to the workflow file so that our app can ignore it...

We'll have to revisit this again after we do the ownership migration done and dusted.  Thanks for the idea :)

**Comment by rachellerathbone** [comment]
Hi @jcdan3. I believe this feature will help with the issue you are having: https://github.com/atlassian/github-for-jira/issues/1303#issuecomment-1226715001

**Comment by rachellerathbone** [comment]
Hey @jcdan3. As we haven't heard from you almost 2 months, I'm going to go ahead and close this issue. Please feel free to reopen if you require further assistance.
