### ISSUE TITLE
Broader environment name support -> Jira environment mapping

### ISSUE THREAD

**Issue by msteward** [atlassian/github-for-jira#594]
## Background
The name of an environment is not always configurable to *exactly* match those specified in https://github.com/atlassian/github-for-jira/blob/master/lib/transforms/deployment.js#L33. 

For example, in Heroku, app names (which map to GitHub environment names when deployed) exist in a global namespace and so must be globally unique . A common convention is to prefix with an org name or something else to make it unique e.g. `orgname-develop`, `orgname-production`

## Suggestion
Relax the name matching rules of https://github.com/atlassian/github-for-jira/blob/master/lib/transforms/deployment.js to allow for environment names *containing* words in the list defined at https://github.com/atlassian/github-for-jira/blob/master/lib/transforms/deployment.js#L33

**Comment by mboudreau** [comment]
Hi @msteward,

We already know about this and someone has suggested it to us before - I can't seem to find the issue for it though.  You're absolutely right that we need better customization of environment names, especially for different locales or conventions.  

At the moment, all new features are on the backburner as we finish the migration over to the Atlassian stack/ownership and then we'll assess which features would have the greatest impact, but I think this is a great suggestion.

Please be patient as we explore this further.  Cheers.

**Comment by tjcunliffe** [comment]
We also need more configurable mapping to Jira environments. Our GitHub Actions pipelines create dynamic environments for each PR - each environment name contains the repo name and PR ID. If it was possible to map environments based on partial matching of the environment name, we could easily solve this by adding a ‘dev-‘ prefix to dynamic environment names. 

The fact that Jira categorises all our environments as “Unmapped” apparently blocks us from using Jira Project Automation rules to automate our workflow, as the “Deployment successful” automation rule trigger contains a mandatory “Environment type” field.

**Comment by fizwidget** [comment]
Hi @msteward @tjcunliffe,

This change has now been implemented, and environment names such as `orgname-production` and `dev-foobar` will be categorised correctly going forward. Examples of the new behaviour can be seen in [these test cases](https://github.com/atlassian/github-for-jira/blob/main/test/unit/transforms/deployments.test.ts#L43) 🙂

Cheers, James

**Comment by thombergs** [comment]
There's more configurability coming with this PR: https://github.com/atlassian/github-for-jira/pull/1070
