### ISSUE TITLE
Does the plugin support self-hosted GHE deployments?

### ISSUE THREAD

**Issue by justin-boyle-ck** [atlassian/github-for-jira#644]
I can't find any mention of on-prem Github Enterprise deployments in the Jira plugin documentation, is this use-case supported?

**Comment by thombergs** [comment]
Hey @justin-boyle-ck,

this app doesn't support GHE on-premise. To integrate Jira with GHE on-premise, you currently have to use the [DVCS Connector feature](https://confluence.atlassian.com/adminjiraserver/integrating-with-development-tools-using-dvcs-1047552689.html).

However, we're working on a similar app like this one to make the connection to GHE on-premise simpler.
