### ISSUE TITLE
Does this app offer the ability to embed code from Github in the confluence document?

### ISSUE THREAD

**Issue by trenagirl** [atlassian/github-for-jira#665]
We have been trying to embed code from Github into a confluence document but it continue to open a new browser.  Is this possible ?

**Comment by mboudreau** [comment]
No.  We're specifically an app to sync jira with github commits/issues/PR/deployments.  We don't do anything with confluence.

[You should be able to use the `Display as Embed` mode in confluence to do what you need if the repository is public](https://community.atlassian.com/t5/Confluence-questions/How-do-I-get-Github-to-embed-in-a-Confluence-page/qaq-p/1770079#M214768).
