### ISSUE TITLE
Jira links not working

### ISSUE THREAD

**Issue by caleb15** [atlassian/github-for-jira#673]
The [feature](https://github.com/atlassian/github-for-jira#link-issues-in-github) that turns JIRA ID's in the body of a PR to links has not working for us since the 25th. This is probably related to https://github.com/atlassian/github-for-jira/issues/657 and https://github.com/atlassian/github-for-jira/issues/658, both of which happened around the same time.

We are on version 1.1.6-AC of the `Github for Jira` Jira app. I don't see any "update available" badge.

**Comment by caleb15** [comment]
Note that it just worked with https://github.com/15five/fifteen5/pull/36454 so it's either working intermittently or just got fixed.

**Comment by caleb15** [comment]
Another engineer of ours said that it has been flaky - it's worked on and off over last week

**Comment by jackiescanlon** [comment]
The same has happened to me twice on two different PRs.

**Comment by rachellerathbone** [comment]
Hey @caleb15 and @jackiescanlon. Can you both try going to Apps > Manage your apps > click on GitHub for Jira > Get started. From the GitHub config page select 'Full' from the dropdown under 'Retry' and then click submit (will need to do for any org where you're having issues). If you aren't an admin in Jira then you'll have to get someone who is to do this.

<img width="1551" alt="Screen Shot 2021-09-01 at 8 54 22 am" src="https://user-images.githubusercontent.com/37155488/131586090-75c779f8-3259-47e0-9488-8ca64870d530.png">

This will resync all your repos and hopefully resolve the issues you are seeing. Please keep in mind, if you have a large number of repos &/or particularly large repos (lots of commits, branches etc) that it may take some time to complete.

Please let us know if resyncing doesn't resolve your issues so we can investigate further.

**Comment by thombergs** [comment]
same issue as in #674

**Comment by jackiescanlon** [comment]
Thanks @rachellerathbone, I followed the instructions you provided. I'll report back if I hear of any anomalies.

**Comment by adrianne-helpscout** [comment]
@jackiescanlon @caleb15, I first raised this issue some days ago in issue #638 and subsequently I opened a support request. The support agent let me know that the issue has been escalated and is now being tracked by [JSWCLOUD-21862](https://jira.atlassian.com/browse/JSWCLOUD-21862)

Running the sync will fix any existing issues, but moving into the future you will experience new issues that exhibit the same behavior, at least that is what I am currently experiencing.

**Comment by jackiescanlon** [comment]
Thanks @adrianne-helpscout, I'll watch that issue as well.

**Comment by thombergs** [comment]
We just fixed an issue around PRs. Please check this comment for the background: https://github.com/atlassian/github-for-jira/issues/674#issuecomment-912404171

**Comment by jackiescanlon** [comment]
Thanks @thombergs!

**Comment by caleb15** [comment]
@rachellerathbone I did a full sync, I'll let you know if it happens again.

**Comment by atrigueiro** [comment]
Closing this issue since it was resolved. Please check @thombergs ' comment above for details.
