### ISSUE TITLE
Improve Smart Commits to allow JIRA IDs in other places of the commit

### ISSUE THREAD

**Issue by crqra** [atlassian/github-for-jira#706]
Hey there 👋🏼 

Is it possible to support having the JIRA ID in the commit's body and footer as well instead of only on the title?

Thanks in advance!

P.S.: I've tried to search beforehand the issue tracker but couldn't find anything related, sorry if it's duplicated.

**Comment by mboudreau** [comment]
Commits don't have a 'title', 'body' or 'footer'.  They simply have a `message` attribute, that's it.   We parse the `message` attribute for any issue keys it might find.  Is there a problem that you've seen from this?

**Comment by crqra** [comment]
Yup, you're right, when I mentioned those three sections I was referring to having them split by lines like you usually do when doing [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).

The problem I've seen is in a commit with a message like this:

```
fix(lang): add missing translations

closes JIRA-1234
```

The mentioned issue `JIRA-1234` never got this particular commit associated in JIRA. Although the PR and branch were associated (I also added the issue ID in the PR title).

I've looked at the [Process issues with smart commits](https://support.atlassian.com/jira-software-cloud/docs/process-issues-with-smart-commits/) page and from what I could tell the issue ID always needs to be on the first line of the commit message and can optionally be prefixed with some text:

```
<ignored text> <ISSUE_KEY> <ignored text> #<COMMAND> <optional COMMAND_ARGUMENTS>
```

Is there something I could've missed maybe?

Thanks!

**Comment by rachellerathbone** [comment]
Hey @crqra. I just took the commit message you provided it as an example and tested it out by replacing the key with one from my own board:

<img width="312" alt="Screen Shot 2021-09-21 at 4 08 52 pm" src="https://user-images.githubusercontent.com/37155488/134120319-faadd4bc-7417-4d05-9b77-565d4de73d45.png">

and I can see the commit is showing up in the dev panel under commits:

<img width="946" alt="Screen Shot 2021-09-21 at 4 12 20 pm" src="https://user-images.githubusercontent.com/37155488/134120603-de530ab6-8f04-4966-a2d5-1d7ad00410e4.png">

We've had some issues in the app recently that have resulted in data not showing up consistently for some customers but these problems should be resolved now. Could you please let me know if you are still experiencing this issue?

**Comment by rachellerathbone** [comment]
Hey @crqra. Just checking in to see if you were able to resolve the issue you were facing. Please let me know if you need more assistance.

**Comment by crqra** [comment]
Hello @rachellerathbone, I've had the opportunity to test this out yesterday and indeed it's working as expected. Not really sure what was the issue that lead me to open this but seems it was definitely something on my end!

Thanks for the help!
