### ISSUE TITLE
Github mitigation when Jira Cloud moves to another Cloud instance

### ISSUE THREAD

**Issue by tobyerin** [atlassian/github-for-jira#707]
Hi,

Currently the client has GitHub account connected to their Jira instance dunkinbrands.atlassian.net.
![image](https://user-images.githubusercontent.com/90350099/132570542-216ab276-e5d4-4f26-8cb9-5a859bc7208c.png)

They plan on merging/migrating to inspirebrands.atlassian.net so I need to understand the impact and what is needed so Github functionality is maintained after the Cloud move.

Two questions:  
1) what is needed to ensure a seamless transition?  Is it just configuring a new entry in the new Cloud instance?  If not, what actions are needed?
2) Will the development panel remain consistent - that everything is seen currently will still look/act the same way once Jira is migrated and links and info related to commits, etc will still work.

Thanks,
Toby

**Comment by KAbakumovAtl** [comment]
Hi Toby,
Thanks for contacting us, I am Konstantin from Atlassian and I am happy to help with your questions.

Currently, after migrating from one Jira Cloud instance to another you will have to install the GitHub App on the new Instance and establish the same integration with the same GitHub Organisation manually. 

After you install the integration in will launch a sync, which will backfill all existing data from GitHub into the new Jira instance. The app will function in absolutely the same way and you should see the same data. As long as you didn't rename projects (so issues have same issue keys) you should see same commits, branches and pullrequests on Jira tickets, which had data on the previous Jira instance.

I'd also recommend to check all Automation Rules and make sure they are identical on both Jira instances. If there were any automation rules set up on dunkinbrands.atlassian.net. (Hence Automations For Jira often used to set up some actions happening on development activity. For example, transitioning ticket status to "In Progress" on new branch creation)

Feel free to reach us out if you'll have further questions

Thank You,
Konstantin

**Comment by mboudreau** [comment]
I'll also add in case it wasn't clear from Konstantin's explanation: migrate your Jira projects first, then add the github app and connect the org for the sync.  If the projects aren't there, it won't "connect" to it when backfilling data.

It shouldn't be too complicated to accomplish and backfilling might take a few hours depending how many repositories/commits/PRs you have.

**Comment by tobyerin** [comment]
Konstantin and Michel,

Thank you so much for the responses.  This is very helpful and clear and we
can communicate back to the client.

Question:  As we are in the middle of the planning/discovery phase of this
Cloud migration, would it be possible to keep the ticket open for a few
days in case the client has any additional questions I can't answer?  Or
would it be best practice to open a separate ticket?  Just let me know the
preferred process.

This assessment ends next week.

Thanks,
Toby

Toby Erin O'Sullivan
mobile: +1 512 799 0185
***@***.*** ***@***.***>
praecipio.com
[image: Atlassian Certified in Jira Project Administration][image:
Atlassian Certified Jira Service Desk Administrator]

**Comment by KAbakumovAtl** [comment]
Sure, we can keep it open, you can ask any further questions here.

Regards,
Konstantin

**Comment by rachellerathbone** [comment]
Hey @tobyerin. Just checking in the see if there is anything else we can help with. Given we're nearing the 2 month mark since we've header anything on this thread, if there is nothing else we can help you with, I'll close this issue.

**Comment by rachellerathbone** [comment]
Hey @tobyerin. I'm going to go ahead and close this issue. Feel free to reopen/reach out again if you need help with anything.
