### ISSUE TITLE
Commits/PRs etc not syncing between GitHub and Jira development 

### ISSUE THREAD

**Issue by AHannAT** [atlassian/github-for-jira#715]
We are seeing similar problems to some of the other bugs in the list; since this last week or so the integration showing development has either lagged or not synced the full data automatically. 

We have done a full manual sync and thats brought everything across up to that point, but since it is still not automatically syncing. 

Possibly this behaviour started after the last release of the app

**Comment by tfmf** [comment]
Seeing the same thing on my end.

**Comment by maxizrey** [comment]
Jira do not see commits, see PR only.
Commits appear after performing full sync perform and Rediscover GitHub repositories.
This Problem started about two weeks ago.

**Comment by thombergs** [comment]
We're currently investigating an issue where commits are not appearing in Jira. We'll keep you posted.

**Comment by tfmf** [comment]
hey guys, any news on this? I have been having to force sync every day which is not very efficient since some of our repos are huge 😅

**Comment by mboudreau** [comment]
@tfmf We think we might have found a workaround over the weekend.  Can you check to see if things are syncing correctly without the need to force sync?  If it's still happening, please let us know and we can investigate further.

There are more changes coming soon that will make things faster and more stable.

**Comment by tfmf** [comment]
I just tested out and it seems to be working 👍🏻

**Comment by rachellerathbone** [comment]
Great to hear it is working for you again @tfmf. @AHannAT can you please confirm that this issue has been resolved for you as well?

**Comment by AHannAT** [comment]
Its working again now. Atlassian have closed the ticket their side as well.

**Comment by rachellerathbone** [comment]
That's great news @AHannAT. I will close this issue as well.
