### ISSUE TITLE
All repos are not syncing with Jira despite multiple attempts

### ISSUE THREAD

**Issue by Barboconnellmw** [atlassian/github-for-jira#749]
This is my fourth time reporting this issue (Github Support #1260734 and #1301154 and Atlassian Support https://getsupport.atlassian.com/servicedesk/customer/portal/48/PCS-55711) so I won't reiterate all that we have tried multiple time to sync since it's documented several times in all those tickets.

I'm happy to sync again under the watchful eye of a support person with access to logs so that it can be tracked in near real-time.  

The Atlassian Support person is jstocker@atlassian.com, please involve him to coordinate things on the Atlassian side.  I can add you to the Atlassian ticket to continue conversations in a non-public forum.

Thanks

**Comment by thombergs** [comment]
Hey @Barboconnellmw 

I'm sorry about that. We're currently investigating an issue where the data flow between GitHub and Jira is stuck in a working queue, which makes everything really slow. We're working towards fixing that, but can't say when it will be fixed, yet.

**Comment by Barboconnellmw** [comment]
Is there a public Atlassian ticket to follow?

**Comment by rachellerathbone** [comment]
Hi @Barboconnellmw. Public ticket is [here](https://jira.atlassian.com/browse/JSWCLOUD-21899?focusedCommentId=2877665&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&error=login_required&error_description=Login+required&state=057883b1-7e95-4359-95f2-46956cdec713).

**Comment by rachellerathbone** [comment]
Hey @Barboconnellmw. We just deployed a fix to prod this morning so please try running a sync again and let us know if you continue to run into any issues.

**Comment by rachellerathbone** [comment]
Hey @Barboconnellmw. I'm going to close this issue as we believe we have resolved the problems that were causing this to happen. Please feel free to reopen and reach out again if you continue to have problems.
