### ISSUE TITLE
PRs not linking to JIRA tickets referenced in commits

### ISSUE THREAD

**Issue by celinakRS** [atlassian/github-for-jira#765]
We are MISSING some PRs from showing in JIRA.  Through some research, I believe the following is happening.

- IF the JIRA number is referenced in the PR TITLE and/or FEATURE branch NAME, then the JIRA ticket gets updated correctly with a link to the PR.  
- If the JIRA number is ONLY referenced in the COMMIT MESSAGE to the feature branch, then upon PR, the JIRA ticket does NOT get updated correctly with a link to the PR.

It would seem logical to scrape the commits inside a PR to get the respective JIRA numbers impacted.  This can be valuable when you have multiple commits for unique tickets inside a single PR.

**Comment by rachellerathbone** [comment]
Hey @celinakRS. We currently only link to PRs if an issue key is provided in the PR title but I can definitely see value in what you are proposing. I'll flag this with 'to triage' so my team can discuss further.

**Comment by rachellerathbone** [comment]
Hey @celinakRS. This has now been added to the team's roadmap. We'll update you again when we can.

**Comment by celinakRS** [comment]
This is likely closed after https://github.com/atlassian/github-for-jira/issues/119 was released.
