### ISSUE TITLE
Deployments integration documentation

### ISSUE THREAD

**Issue by mikefede** [atlassian/github-for-jira#772]
Hi, 
Can anyone point us to more information about how the Deployments integration works? We are seeing data from GitHub Actions showing up under Builds, but we don't know how to Jira gets deployment information from GitHub.

Also we noticed that there is a brief reference to the new build and deployments integration in the README in the old-master branch but there is no reference to this new capability in the main branch. 
https://github.com/atlassian/github-for-jira/blob/old-master/README.md#support-to-github-actions---new

@atrigueiro I noticed that you closed Issue #310, which was a request to add this capability to show deployment info in Jira. Can you help us with where to find more information on how this integration works?

Thank you!

**Comment by rachellerathbone** [comment]
Hi @mikefede. You won't see any data related specifically to deployments in the details panel.

![Screen Shot 2021-09-24 at 11 54 27 am](https://user-images.githubusercontent.com/37155488/134606572-434aceb2-1f97-4bf9-b14b-31515cbdb9fb.png)

But if you click on any item in that list to open the dev panel, then click on the deployments tab, you will see data there, assuming that you have added a deploy.yml file in your .github/workflows directory.

![Screen Shot 2021-09-24 at 11 55 30 am](https://user-images.githubusercontent.com/37155488/134606764-b6446f2f-4a01-482f-b2e6-22c89f6b5933.png)

If you don't already have a deploy script set up, please feel free to use the one I have in [this repo ](https://github.com/rachellerathbone/sandbox/blob/main/.github/workflows/deploy.yml) as a guide.

**Comment by atrigueiro** [comment]
Hey @mikefede, in addition to what @rachellerathbone said above, you'll also be able to see deployments in the details panel next to releases - if you have any configured in your GitHub Actions as she mentioned.
<img width="400" alt="Screen Shot 2021-07-26 at 3 05 35 pm" src="https://user-images.githubusercontent.com/58801956/134607528-2fc9b4b6-c826-49f6-9273-14978f068fb5.png">

**Comment by rachellerathbone** [comment]
Hey @mikefede. I've just created a ticket in our backlog and will see if someone on the team can pick it up next week.

**Comment by lok225** [comment]
Hi @rachellerathbone. Are there any news regarding this?

**Comment by rachellerathbone** [comment]
Hi @lok225 and @mikefede . We've added [builds](https://github.com/atlassian/github-for-jira/blob/main/docs/builds.md) and [deployments](https://github.com/atlassian/github-for-jira/blob/main/docs/deployments.md) docs to the repo. Please let me know if these help.

**Comment by joseaminan** [comment]
I found this issue searching some solution on google. I have tried the github action and it works great. Thanks so much

**Comment by rachellerathbone** [comment]
Great to hear @joseaminan! @lok225 and @mikefede I'm going to close this issue as I believe this has been addressed. Please feel free to reopen if you need further assistance.
