### ISSUE TITLE
Jira Data center support

### ISSUE THREAD

**Issue by timja** [atlassian/github-for-jira#775]
I see https://github.com/atlassian/github-for-jira/issues/547 was closed because it was about server support.

We use Jira data center and it would be nice if we could use this instead especially since it talks about that connector being end of life after server ends? https://github.com/atlassian/github-for-jira/issues/547#issuecomment-883875974

**Comment by ccrolf** [comment]
Hi Timja, 

this app only support Jira Cloud as it's built on top of a Cloud-only integration framework.

Did you reach out to Atlassian support for options on [how to integrate GH Cloud with Jira server/DC](https://confluence.atlassian.com/jirakb/add-github-organization-repositories-to-jira-software-815256707.html)? The mechanism for server/DC is much better suited for cross-firewall communication.

Cheers,
Christian

**Comment by timja** [comment]
We have it integrated but it often gets rate limited with the 5000 requests per hour that the OAuth app gets
