### ISSUE TITLE
Implementation (optional parts)

### ISSUE THREAD

**Issue by andymckay** [atlassian/github-for-jira#8]
- [ ] Linkifies JIRA identifiers `[SENG-1234]` in GitHub UI - Commit Messages, Reviews, Issues and Pull Requests
- [ ] Linkifies JIRA identifiers `[SENG-1234]` in GitHub notifications - email digest
- [x] Associates JIRA project to 1 or more GitHub repositories
- [x] Associates one GitHub repository with 1 or more JIRA projects

**Comment by rachellerathbone** [comment]
Hi @andymckay (again). Added the to triage label to this one as well for my team to look into 😄

**Comment by rachellerathbone** [comment]
Hi @andymckay. I've created a ticket in our backlog for someone on my team to investigate implementing your suggestions. We'll keep you posted on the progress. Please stay tuned.
