### ISSUE TITLE
Multiple JIRA instances

### ISSUE THREAD

**Issue by NathanHazout** [atlassian/github-for-jira#819]
What happens if 2 companies share the same GitHub organization, but each have their own JIRA instance?

Company A linked their JIRA to the org, a long time ago.  
Today, I linked my JIRA (Company B) to the org. It did not complain, it picked up the repos, and the commits are appearing successfully in my tasks.

HOWEVER, the link generation goes to company's A instance. Meaning, when I write `[AA-001]`, the string is turned into a link to JIRA, but not the correct instance.

What's the expected behavior? Best practices?

**Comment by atrigueiro** [comment]
@NathanHazout Since we haven't heard back in a few months, I'm going to close this one. Please reopen it if you're still affected by the scenario mentioned. Cheers.

**Comment by dorkovitch** [comment]
Hello - we're facing a similar scenario.  Already have an existing github org linked to an existing Jira implementation.  Have had another group start up their own separate Jira implementation that would like to link to the same existing org.  Based on the above, it sounds like we could face a similar issue (Company B commits showing up in Company A's logs).

Curious if any progress was made in this area yet or no its not on the radar any more?  Thanks!

**Comment by manishag-sportsbet** [comment]
Hi, We have a similar scenario. Curious if there's now a fix or workaround for this? Cheers,

**Comment by mboudreau** [comment]
I'm going to go ahead and reopen this.  I believe this is still an issue currently.  Just to confirm, is this only an issue for issue linking within Github?  If the issue linked is tied to more than jira instance, how would you expect it to display to show the difference between the 2?

**Comment by rachellerathbone** [comment]
As we haven’t heard from anyone on this issue in a while, I’m going to go ahead and close this issue. Please feel free to reopen if you still require assistance and would like us to look into this further.

**Comment by woody-apple** [comment]
Hi there, this would be very helpful for our Matter project: https://github.com/project-chip/connectedhomeip/ as we have multiple members looking to use a single github project, with multiple jira installations.

**Comment by frednntelia** [comment]
Hi there, same here.
We use our GitHub org with many teams and host many repositories in it.
Some belong to teams that traditionally use a separate Jira instance.
We would like to integrate with e.g. Jira Cloud instance A to repository 1, and integrate with Jira Cloud instance B to repository 2, both within the same organisation.

Another issue with this setup is the way GitHub for Jira advertises itself to GitHub users upon new repository creation.
There is a button to simply add this integration to the new repository upon creation.
However, considering that we want to have two instances of Jira to pick from, what would this convenient install button look like in the future, when multiple Jiras to one GitHub Org will be supported?

The best workaround at the moment is to use distinct marketplace apps for distinct integration pairs.
I'd rather use one solution and configure it for the given integration matrix.

**Comment by mendhak** [comment]
Would be good to get some attention on this. Large corporates can have multiple Jira instances rather than one, especially if they've grown through acquisitions or restructuring.

**Comment by jezierskj** [comment]
@frednntelia do you by any chance have any documentation on how such workaround setup can be achieved? 
The Jira app available on Marketplace doesn't seem to accept multiple installations: https://github.com/marketplace/jira-software-github/

**Comment by asud1011** [comment]
We are curious as to why this issue has been closed without a resolution. We are currently experiencing a similar problem, and since we have multiple Jira instances maintained by different teams within our company, it is imperative that Atlassian addresses this issue/case promptly.

**Comment by tjaiani** [comment]
Hi, we are facing same issue where we need to connect 1 github org to 2 Jira instances and it's quite critical. Any suggestions/workarounds/solutions for this? 

Thanks

**Comment by RHawley-rms** [comment]
Hi github-for-jira team, We facing the same issue and need a solution.  We are the main CI/CD team for Cloud Services at Moody's and have different OU's onboarding with us (single Github Org) and they have their own Jira orgs.  Please consider reopening and Spiking a solution.  Thank you.   

cc: @Ryan-Yuanqing-Jiang

**Comment by sumeetssmakamai** [comment]
Hi Github Team, 

We are having a similar scenario, where we wish to integrate two Jira Instances to One Github Instance.
Please let us know if there is a possible solution.
