### ISSUE TITLE
Question: Barriers to GHES and DVCS Comparison

### ISSUE THREAD

**Issue by aidan-mundy** [atlassian/github-for-jira#820]
Hello all, a couple of quick questions from a GHES user:

What are the current barriers to GHES support (discrete tasks, larger principles, etc)?

What functionality does this app provide that the DVCS connector does not? 

Does the DVCS connector have any functionality that this app does not?

**Comment by rachellerathbone** [comment]
Hey @aidan-mundy. As it's been over a month since we've heard from you, I'm going to go ahead and close this issue. Please feel free to reopen/reach out again if you need help with anything.
