### ISSUE TITLE
Mapping pending to in-progress

### ISSUE THREAD

**Issue by mattcolman** [atlassian/github-for-jira#821]
I've found sometimes Github actions sends a pending deployment that never resolves to a successful deployment, causing the deployments view to show an in-progress spinner forever. 

I think the cause of this was simply committing two commits to master in quick succession, causing the first deployment to remain in pending.

**Comment by yvonnevictoria** [comment]
Hey @mattcolman,

I've tried to reproduce this error and have experienced a different behaviour. When running two GitHub workflows in quick succession, the JIRA card shows `X incomplete builds` and the deployments view shows the workflow as pending. When the workflow has run successfully and you refresh the page, all builds look normal. Could you give me the steps to reproduce this issue and a screenshot of what you are experiencing?

At times, we are finding some builds are not appearing and the incomplete builds number is incorrect. We are looking into this as a separate issue.

Thanks for your time raising and discussing this issue with us.

Yvonne

**Comment by yvonnevictoria** [comment]
Hey @mattcolman,

As we haven't heard from you in a while, I'll be closing this issue. If you'd like us to look into this further, please feel free to reopen this issue.
