### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by nestor-fluidra** [atlassian/github-for-jira#834]
We installed the app yesterday in our Jira instance: https://riiotlabs.atlassian.net/

The Sync Status remains in Pending forever.
We have uninstall and install the app several times with the same result.
We have reduced the amount of repositories to sync into 3.

In other words the synchronization is not happening.
Please, help.
BR

**Comment by nestor-fluidra** [comment]
Dear @bgvozdev , thank you so much for your support. Actually our repositories synchronized about 6 hours ago, which is more or less the time when you told us that it was fixed.
![image](https://user-images.githubusercontent.com/84389933/138048741-7dcade06-0153-45bd-8662-ed0c65640cc7.png)

**Comment by bgvozdev** [comment]
Hey @nestor-fluidra , we have an issue to track the old tokens problem #835 , please feel free to update/watch it. I'm going close this one as the original problem was solved. Thanks!
