### ISSUE TITLE
Github is not getting synced with JIRA for past 1 week - Github integration is still in pending status

### ISSUE THREAD

**Issue by rgprotech** [atlassian/github-for-jira#837]
Github is not getting synced with JIRA for the past 1 week - Github integration is still in pending status
<img width="1791" alt="Screenshot 2021-10-20 at 10 57 12 AM" src="https://user-images.githubusercontent.com/91119214/138033329-31449b61-9b40-4c8d-8422-0602a0a9c429.png">

**Comment by bgvozdev** [comment]
Hey @rgprotech , thank you for providing the URL.

I have checked your installation, and it seems to be stuck in "disabled" state. To be honest, I have no idea how it managed to go to that state cause we recently removed Enable/Disable functionality from the marketplace recently. https://community.developer.atlassian.com/t/are-enable-disable-events-still-supported-in-the-app-lifecycle/38452 I'll clarify this tomorrow with the responsible team.

As a mitigation, I recommend you to reinstall the app. (Assuming you already tried that, JFYI: during the past few days we experienced an issue that broke commit syncs. It was fixed today few hours ago, therefore the new attempt should be different from your previous ones.)

I apologies for the inconvenience. Looking forward to hear from you.

Kind regards,
Boris.
