### ISSUE TITLE
Support Deployments with a "branch & merge" strategy

### ISSUE THREAD

**Issue by thombergs** [atlassian/github-for-jira#855]
When using a git flow like branching strategy with `feature` branches and a `main` (or `release`) branch in which they get merged, Deployments won't show up in Jira after the merge.

If I push a commit with issue key `KEY-1` into the `feature` branch, the deployment shows up connected with the `KEY-1` issue in Jira.

When I merge the `feature` branch into `main`, the deployment that is triggered from the `main` branch, doesn't show up in Jira (i.e. it's not being connected with the `KEY-1` issue.

I guess we need to implement some smart logic that crawls all commits that have been made on the `feature` branch, but are not yet in the `main` branch, and check those commits for issue keys and then add those issue keys to the deployment

**Comment by eialanjones** [comment]
+1

**Comment by jakila** [comment]
I came across this issue after reading this line https://github.com/atlassian/github-for-jira/blob/075c4339968fdaafc781ff581acf5a32398f4da7/src/transforms/deployment.ts#L67
If i am reading this correctly, then only the last commit is considered when processing deployments, isn't it?

I want to highlight another use case were this is quite unfortunate:
We have some environments that can be updated only during certain maintenance windows (i.e. once a week). Usually there are five to ten commits on our "main" branch between each deployment to these environments.  Each commit has an jira issue key.
However, as only the last commit is parsed for jira issue keys, at most one jira issue gets the right deployment state. And all others issues show as "not deployed".

**Comment by rachellerathbone** [comment]
Hey @jakila and @eialanjones. Good news, we've just rolled an update for this out to all customers. Please let us know if this now works as expected.

**Comment by jakila** [comment]
That's great news! 
I just did a quick check and it seems to be working for us. Will take a few more days (and a few more deployments) to verify it is working as expected. 
But already now the deployment view in our Jira looks more complete than ever before 🚀 

A big "Thank You" to atrigueiro, rachellerathbone and everyone else working on the topic!

**Comment by rachellerathbone** [comment]
That's great to hear @jakila 🎉

**Comment by palexcast** [comment]
Hi, we are experiencing a similar issue.
We have a single branch (main) which we deploy to, and we mark each commit with the task id in the name.
On every commit to the main branch we deploy to our development environment. The workflow will then wait for a review /approval before deploying to staging, and then the same for production.

All our tasks are displayed as deployed to development as expected, but only the last one to go staging/prod will be updated as released to the correct environment.

**Comment by pdyck** [comment]
Hey, we just had our first production deployment with this Jira for Github integration. We expected the deployment status to change for all relevant issues but nothing happened.

I investigated the code and found this: when looking for the commit messages since the last successful deployment, you return `undefined` when there hasn't been a successful deployment yet. Since this was our first deployment only issue keys from the last commit messages were extracted (merge commit). The next deployment will extract issue keys from all deployments since our first deployment. Thus, the deployment status for the issues in the first deployment will never be updated.

https://github.com/atlassian/github-for-jira/blob/main/src/transforms/deployment.ts#L67

Suggestion: return all commit messages when there are no previous successful deployments. Is this feasible or would you run into scalability issues?

**Comment by rachellerathbone** [comment]
Hey @palexcast and @pdyck if I'm understanding correctly, it looks like your issues are related to deployments but are different from the resolved issue in this thread. To make sure issues stay focused on one problem, and to make sure your messages don't get lost in this thread, I've done ahead and opened up new issues for your separate concerns:

- @palexcast https://github.com/atlassian/github-for-jira/issues/1041
- @pdyck https://github.com/atlassian/github-for-jira/issues/1042

Please feel free to add any additional information &/or screenshots to your respective issues.

**Comment by rachellerathbone** [comment]
@jakila I'm going to go ahead and close this issue. If you notice anything not working as expected regarding the support of issue keys multiple branches + commits, please feel free to reopen this and reach out again.
