### ISSUE TITLE
Can't configure integration / connect to GitHub organization

### ISSUE THREAD

**Issue by fc-reus** [atlassian/github-for-jira#868]
Can't configure integration / connect to GitHub organization.

Error message:
"Looks like something went wrong!
Session information missing - please enable all cookies in your browser settings.
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try adding an organization again in Jira."

Activated all cookies and even tried in different browsers, still not working.

**Comment by rachellerathbone** [comment]
Hey @fc-reus. Just to give you an update on this: one of my team members has an open [PR](https://github.com/atlassian/github-for-jira/pull/871) to try and resolve this issue. It's currently going through the review process and should hopefully be merged this coming week. Thanks for your patience on this.

**Comment by pat-bao** [comment]
Hi @rachellerathbone, we're having the same issue as @fc-reus, however we've just seen that the PR has been closed. We're currently unable to link Jira and GitHub, is there a workaround to this issue?

**Comment by pat-bao** [comment]
It seems the issue was cookie related and we've now connected it correctly.

**Comment by fc-reus** [comment]
How did you manage to connect it?

**Comment by mboudreau** [comment]
@fc-reus it'll work if you enable 3rd party cookies and refresh the landing page.  There was a security flaw that was fixed but made it that the user needs to have those cookies enabled for it to work until we get the proper solution out. We have one in the works, but as a workaround your just need to enable that setting in your browser.

**Comment by mboudreau** [comment]
@fc-reus We've had a fix for the blocked 3rd party cookies that just went out.  You can now re-enable your cookie security policy as it was before.  Let me know if this is still affecting you or you can please close this issue if you're satisfied.  Thanks.

**Comment by fc-reus** [comment]
Unfortunately I already used the workaround to connect it, so I can't test it anymore

**Comment by mboudreau** [comment]
I'm going to close this issue in that case.  Open it again if you ever have more issues surrounding this.  Thanks!
