### ISSUE TITLE
Does this app support Github enterprise yet?

### ISSUE THREAD

**Issue by Karthickvr** [atlassian/github-for-jira#896]
Hi there,

I'm about to setup the JIRA on cloud/Github enterprise integration using this app as per the link: https://support.atlassian.com/jira-cloud-administration/docs/integrate-with-github/.  

Wondering is the github enterprise integration is supported yet?

Thanks

**Comment by mboudreau** [comment]
It works with Enterprise Cloud (hosted on github.com) but doesn't work with Enterprise Server (self-hosted) :)

**Comment by mboudreau** [comment]
Does this answer your question?  If so, I'll close this issue.  Thanks

**Comment by Karthickvr** [comment]
Yes, that response answers to the question.. Will raise any new issues if we find any issues on integrating with JIRA/Github, however happy to close this issue, as it is an initial clarification.
