### ISSUE TITLE
unable to configure plugin since latest change

### ISSUE THREAD

**Issue by froggr** [atlassian/github-for-jira#904]
We reinstalled the plugin today and when loading the post install page we see the loading spinner for a minute or so and then the following error.  The persists across all major browsers.

<img width="423" alt="Screen Shot 2021-11-10 at 10 57 00 AM" src="https://user-images.githubusercontent.com/4052787/141136276-94addfb9-738f-4040-b0bb-f3a0860bbbc8.png">

In the devtools/network we see a `400` coming back from:
https://github.atlassian.com/jira/configuration?xdm_e=https%3A%2F%2Ftimelessmedical.atlassian.net&xdm_c=channel-com.github.integration.production__gh-addon-admin&cp=&xdm_deprecated_addon_key_do_not_use=com.github.integration.production&lic=none&cv=1001.0.0-SNAPSHOT&jwt=`{JWT HERE}`

with the following error: 

{
  "message": "Unable to decode JWT token: Error: Signature verification failed for input: `{same JWT}` with method sha256"
}

**Comment by mboudreau** [comment]
@froggr Thank you for letting us know.  Let me look into the logs to figure out what's going on.  Cheers.

**Comment by mboudreau** [comment]
@froggr I think some cookies might have gotten mixed up somehow.  Could you please try again as we've released a fix that should alleviate this issue.

**Comment by atrigueiro** [comment]
@froggr I'm going to go ahead and close this issue. If you notice anything not working as expected regarding the installation, please feel free to reopen this and reach out again.
