### ISSUE TITLE
Integration with Jira after migration & merge

### ISSUE THREAD

**Issue by roger-sr** [atlassian/github-for-jira#943]
Hello,

We are migrating Jira from server to cloud and will merge it with another Jira cloud site.
We have few questions regarding the integration between Jira and Github:
1. We will use JCMA to migrate from cloud to server, meaning that issue ID will be changed, while issue key will remain the same. Will it break the integration ?
2.  We will be merging two jira instances, there are duplicated project keys, we will need to rekey one of the projects, will it break the integration ?

Thanks,
Regards,
Roger

**Comment by mboudreau** [comment]
@roger-sr I'm not 100% but I'm fairly sure that integration data doesn't migrate with JCMA.  But no matter, all you have to do is add the app once the migration is done and add the github org again to do a backfill of the data.  The app looks for issue keys throughout to link everything together.  It might take a little while to complete depending on how large your github org is but it will prioritize more recent repositories so it doesn't affect your work too much.

Let me know if this answers your question.

**Comment by roger-sr** [comment]
Hi @mboudreau , Thanks for your answer. It's great that the app looks for issue keys instead of issue ID. I will close this ticket.  Cheers,
Roger
