### ISSUE TITLE
Jira to Github integration. 

### ISSUE THREAD

**Issue by gulyarauff** [atlassian/github-for-jira#979]
Hi 
I am trying to integrate my jira to github  but I am unable. I was able just select the app and send request . and NOTHING.
When I click on settings I get the message You dont have access to Jira setting or atlassian admin

**Comment by mboudreau** [comment]
You're going to have to explain it a bit more than that.  What exact steps did you do?  Can you provide screenshots along the way?  Did you get an error of some kind?  Did you install the app from Jira or from Github?  Are you an admin in Jira and the Github org you want to connect?

Thanks.

**Comment by atrigueiro** [comment]
Hi @gulyarauff Since we haven't heard back in a month, I'm going to close this one. Please reopen it if you're still having issues using the integration. Cheers.
