### ISSUE TITLE
I can't link my issues to my github repository

### ISSUE THREAD

**Issue by wiljmb** [atlassian/github-for-jira#981]
Hello, I installed the app on github and on jira, according to jira the connection between the two was made, but when I go to my project and go to code I can't add any github repository, also if I go for the incidence and give it to create branch sends me directly to bitbucket and won't let me link to github

**Comment by mboudreau** [comment]
> but when I go to my project and go to code I can't add any github repository
Can you elaborate on this please?  I'm not sure what part of the system you're accessing.  Screenshots would be helpful.

> give it to create branch sends me directly to bitbucket and won't let me link to github
Sadly, the create branch in jira only works with Bitbucket at the moment.  We are working to get this fixed in the new year, but for now, to create new branches you'll have to create them the ol' fashioned way.

**Comment by wiljmb** [comment]
A thousand apologies, my English is not very good, I was referring to the project>code section

![Captura de pantalla de 2021-12-16 01-52-10](https://user-images.githubusercontent.com/44048176/146316171-7eab7725-8f04-4616-964a-b885c9caba68.png)

**Comment by wiljmb** [comment]
is it mandatory that i have to link an organization on github? I can't do it with my personal account only?

**Comment by thombergs** [comment]
Hey @wiljmb,
a personal account is a special kind of "organization". So, yes, you can connect repositories from your personal account.

**Comment by thombergs** [comment]
As for the "Code" page, you will see all repositories there that are in an org that you have connected and in which you have used  a valid Jira issue key in at least one commit message, branch name, or PR title.

**Comment by wiljmb** [comment]
@thombergs 
I already tried to do it as you mention but it does not recognize the repositories of my personal account, the same when I create a new project and I want to link my github repositories from my personal account it does not give me the option it tells me that I require an organization

**Comment by thombergs** [comment]
Can you please post a screenshot of  where it tells you that you require an organization? I don't recognize that error message

**Comment by wiljmb** [comment]
@thombergs 

Here are two screenshots in one is where they ask me to have an organization and in the other you can see that it is configured as indicated, from the part of the github configuration the jira app has all the permissions as indicated in the configuration manual .

This only happens to me with my personal account, but when I create an organization in my github and create a repository in it, it already lets me select a repository when creating a project in jira

![jira](https://user-images.githubusercontent.com/44048176/146693888-59cb827c-d5d7-4c64-8d59-b0ef3e4c82dc.png)

![github](https://user-images.githubusercontent.com/44048176/146693892-f9594501-b31e-4f84-ae79-4734ed169b26.png)

**Comment by bgvozdev** [comment]
Hey @wiljmb , thanks for the screenshots. What happens if you click "Connect GitHub organisation" on the 2nd screenshot and select the org you want to connect?

**Comment by wiljmb** [comment]
Hey @bgvozdev, in that case if the organization's repositories recognize me, but what I want to know is if there isn't a way to link jira to my personal github account without creating organizations

**Comment by bgvozdev** [comment]
Ah, I think I got you now. @wiljmb .  You are talking about the first screenshot, no the 2nd one, right?

These are similar, but a little bit different features. On the 1st screenshot you can "connect" an org to Jira and that would allow you to have some additional nice things (e.g. automatically create repositories). AFAIK, it works only with orgs and doesn't work with your personal accounts.

However, if you only want to see you commits/branches/pull requests in Jira issues, you don't need to to that step at all. All you need to do is to add your org/private account to the page from your 2nd sceenshot and then push commits/branches/PRs with issue keys in commit messages/names or branches/ names of the PRs . Once you do this, you should be able to view your development information inside Jira issues regardless what kind of GitHub account you have, being that a personal one or an org.

For more information you could check this section of README: https://github.com/atlassian/github-for-jira/blob/main/README.md#send-data-and-use-the-integration

How does it all sound to you?

**Comment by bgvozdev** [comment]
Hey @wiljmb , we haven't heard back from you. I'm going to close the issue for now, please feel free to reopen if you still have questions or concerns.
