### ISSUE TITLE
App isn't working after reinstall

### ISSUE THREAD

**Issue by joshualpatterson** [atlassian/github-for-jira#984]
I'm not sure how to specify the issue because the app simply doesn't seem to be working. We've uninstalled and reinstalled several times, the backfill runs and eventually indicates `FINISHED` as expected, but nothing shows up in our issues in JIRA.

We've created commits, pull requests and branches all with the JIRA issue ids in several different formats but still nothing appears to be linking back to the JIRA issues. Is there some sort of additional configuration step we need to take or maybe a conflict of some sort we should look for?

This might be related: when we go to "Manage your apps" in JIRA and expand this app it still has the initial view with a "Get Started" button, even after we click it and do the configuration.
![image](https://user-images.githubusercontent.com/73613472/146416278-cf87e995-b1ca-4422-ae55-3808ad8cf149.png)
![image](https://user-images.githubusercontent.com/73613472/146416615-ad26452d-3107-4c6e-a1b2-c78bf5558afa.png)

**Comment by joshualpatterson** [comment]
Some additional screenshots for sanity-checking...

Pull Request with issue id in title:
![image](https://user-images.githubusercontent.com/73613472/146417344-53d3b6dc-ff71-435d-a7d7-9aa3104996f5.png)

Commit inside PR with issue id in title:
![image](https://user-images.githubusercontent.com/73613472/146417499-576fc3c9-0e2d-450b-b50b-1a0c6214df57.png)

**Comment by mboudreau** [comment]
@joshualpatterson Hm, interesting.  I'm looking at the logs and it seems like we're getting the data but we're having an issue communicating with the Jira API to save it.  Let me look further into this.

**Comment by ccrolf** [comment]
Hi @joshualpatterson do you mind raising this with Atlassian support so they can assist with the investigation?

**Comment by joshualpatterson** [comment]
@ccrolf I'll try sure. In the meantime we bought and tried out a similar app and it worked so that's the solution for now

**Comment by SusiGrimes** [comment]
@joshualpatterson which app was that?

**Comment by joshualpatterson** [comment]
@SusiGrimes it's called Git Integration for Jira Cloud.

**Comment by rachellerathbone** [comment]
Hey @joshualpatterson. Are you planning on using our app again in future or are you sticking with the other app installed? Happy to try and help resolved the issue you were having if you want to switch back.

**Comment by atrigueiro** [comment]
Hi @joshualpatterson, since we haven't heard back in a couple of months, I'm going to close this one. Please reopen it if you're still having issues using our app. Cheers.

**Comment by DanielKorsa** [comment]
Currently having exactly the same issue. Any fixes available?
