### ISSUE TITLE
Can't connect to organization after re-install

### ISSUE THREAD

**Issue by gadigrin** [atlassian/github-for-jira#985]
I can't seem to be able to connect back to my github account after reinstalling.

After uninstalling I reinstalled, clicked get started, connect github organization, it opened a new tab "logging into your organization" for a few seconds and then the following error page:
![image](https://user-images.githubusercontent.com/93197544/146455619-ef2bbf48-d73b-47e8-bbcc-67d642813b43.png)

**Comment by mboudreau** [comment]
@gadigrin What's your jira domain?

**Comment by mboudreau** [comment]
Actually, this might be caused by a known issue that we're fixing right now.  Could you please try to clear your cookies for `github.atlassian.com` and try again?  Thanks :)

**Comment by atrigueiro** [comment]
Hi @gadigrin, since we haven't heard back in a few months, I'm going to close this one. Please reopen it if you're still having issues. Cheers.
