### ISSUE TITLE
Feature Flag SUPPORT_BRANCH_AND_MERGE_WORKFLOWS_FOR_DEPLOYMENTS

### ISSUE THREAD

**Issue by rbehle** [atlassian/github-for-jira#986]
Is there any timeline for when this feature flag becomes publicly available?

**Comment by thombergs** [comment]
Hey @rbehle,
we're planning to test that thoroughly next week and will hopefully start rolling it out within the week.

**Comment by rbehle** [comment]
@thombergs Thanks for the fast reply. That's is great news because it would simplify our process dramatically.

**Comment by thombergs** [comment]
Hey @rbehle,
we're probably going to start rolling out this feature today or tomorrow over the . 

If you tell me your Jira site URL, we can include you in the firs

**Comment by rbehle** [comment]
Thank Tom, I just sent you a private message.

**Comment by thombergs** [comment]
Hi @rbehle,

I have just activated the feature flag for you. Please have a look at [these docs](https://github.com/atlassian/github-for-jira/blob/update-builds-docs/docs/deployments.md) for some information (they are not merged into `main`, yet).

**Comment by rachellerathbone** [comment]
Hi @rbehle. Could you please let us know if branching for builds and deployments is now working as expected?

**Comment by atrigueiro** [comment]
Hi @rbehle, since we haven't heard back in a month, I'm going to close this one. Please reopen it if you're still having issues. Cheers.
