### ISSUE TITLE
View all JIRAs per Github release?

### ISSUE THREAD

**Issue by cpp77** [atlassian/github-for-jira#997]
(Not an expert on Github or JIRA, I'm just the person investigating)

Is there a way to configure/use Github and JIRA to automatically aggregate all JIRAs (possibly across multiple branches) contained within a release?

So I click on a release, it shows the branches within that release and for each branch it shows the relevant JIRA? Or, a collapsed list of all JIRAs within the release.

**Comment by thombergs** [comment]
Hi @cpp77,

when you say "release", I guess you mean a release in GitHub, right? No, there is no such functionality.

I'll keep this issue open as a potential idea for the future.

**Comment by lucasff** [comment]
I am looking forward since ages to have something that integrates with releases. It was always a manual process to link a ticket to a "fix version" and have full code discoverability using the released versions. In the end, I want to know when a ticket was released (included in a tag);

**Comment by mboudreau** [comment]
@lucasff Have you looked into the "deployments" functionality?  It might be closer to what you're thinking of.  The "release" aspect of Github doesn't have an equivalent in Jira yet.

**Comment by rachellerathbone** [comment]
Hey @cpp77. As we haven’t heard from you in a while, I’m going to go ahead and close this issue. Please feel free to reopen if you still require assistance.
